Shadow Hints by Textfyre begins here.

To Send hints for (x - a number):
	if x is 1 and XML is in use:
		select the hints channel;
		say "		<hints title=[quotation mark]Chapter 1[quotation mark]>";
		say "			<topic title=[quotation mark]Help! Someone's coming! What can I do?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>It wouldn't be a good idea to be found in here.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>But there's no way to get away through the door, or the window.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>You'd better hide somewhere.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>The cot's too small. There's only thing big enough...</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>Remember, Grandfather clocks have large cabinets where the penduluums are...</hint>";
		say "				<hint id=[quotation mark]6[quotation mark]>Try hiding inside the clock! And better do it quickly!</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]Why is everyone here so interested in clocks?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>In the world of Klockwerk, clocks - and clockwork mechanisms - are the most important things in the world. More important even than people.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>That's what makes the world of Klockwerk an interesting place to be - but sometimes, it can also be a dangerous and unfriendly place.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>As Wren is going to find out...</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]This is frustrating - I can't hear what they're saying![quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>The Abbot is just visible through that keyhole. Maybe you could hear something there?</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>But maybe listening at the keyhole still isn't enough. If there was something you had that could make it louder...</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>There's an old trick to listening at keyholes: using something cup-shaped to amplify the sound...</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>Try putting your glass against the keyhole.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]They've gone. What should I do?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Sounds like you need to tell someone what you've heard.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Get out of the clock and get out of the Abbot's room, before he comes back!</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>The door is to the west - just type WEST to go that way.</hint>";
		say "			</topic>";
		say "		</hints>";
		select the main channel;
	if x is 2 and XML is in use:
		select the hints channel;
		say "		<hints title=[quotation mark]Chapter 2[quotation mark]>";
		say "			<topic title=[quotation mark]Help, I'm lost in the Abbey![quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>The Abbey can be a big and confusing place, with lots of rooms.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>However, you should soon start to get your bearings. There's a long central hall, and other rooms coming off it.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>In particular, at the end of the hall is the yard - and that leads onto the Cathderal...</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]What am I supposed to do?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>You need to find the Archbishop, in the Cathedral of Time.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Right now you're in the Abbey of Time, so you'd better leave.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Once you're in the Hall of the Abbey, you need to keep going southwest until you get out.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>Except there's a spanner in the works, and that's Calvin.</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>Either you need to find another way out of the Abbey, or some way of shifting him.</hint>";
		say "				<hint id=[quotation mark]6[quotation mark]>Time to explore - and you might find Brother Horloge of some interest... </hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]Help! I keep getting caught by Drake[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Drake is a big pain in your life, Wren. He's the worst there is.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>But luckily, he's boring. Everything he does is clockwork. He likes to stick to a pattern.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>If you can work out which order he walks around the Abbey in, you might be able to dodge him.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>Also, if he's approaching a room where you're standing, you might be able to hide.</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>Several of the rooms offer hiding places.</hint>";
		say "				<hint id=[quotation mark]6[quotation mark]>Try hiding under the Refectory tables - or in the Pantry in the Kitchen!</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]I've seen some keys but I can't get my hands on them![quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Of course you can't, they're not yours!</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>But you could probably borrow them.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Except Brother Horloge won't let you. Every time you try and take the keys it's too distracting for him. Perhaps you could distract him in return.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>There seems to be something he wants. Can you figure out what it is?</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>Brother Horloge is a great drinker of tea. Time to brew up a cup!</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]I can't make the machine in the Kitchen work![quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Like all good clockwork machines, the Tea Maker needs a lot of different things to make it go.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Make sure you EXAMINE it closely. Try pulling the lever to turn it on.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Some of the things you need are obvious. You can't make tea without tea leaves, or a cup.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>When you've found some tea, put it in the basket. When you've found a cup, put that in the bracket.</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>You'll have to fill the kettle up too.</hint>";
		say "				<hint id=[quotation mark]6[quotation mark]>But what about this missing gear?</hint>";
		say "				<hint id=[quotation mark]7[quotation mark]>Have you seen anywhere which might stock replacement gears?</hint>";
		say "				<hint id=[quotation mark]8[quotation mark]>Perhaps Brother Reloh can help? (Or, perhaps not).</hint>";
		say "				<hint id=[quotation mark]9[quotation mark]>Take one of the new gears from the Cabinet in the Scriptorium. Then put that into the Tea Machine.</hint>";
		say "				<hint id=[quotation mark]10[quotation mark]>Still stuck? Just pull the lever, and watch it go!</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]What should I do with the owl?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>If you can't think of anything to do with the owl yet, you must not need it yet.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>If you still can't think of anything to do with the owl, maybe there isn't anything to do with the owl.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>It's Brother Horloge's owl. And it's asleep.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]No-one seems to want to talk to me![quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Most of the monks are very busy. And very crotchety.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Some of them will talk to you - the Abbot, for instance, if you're brave enough to go back to his quarters.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Try asking him about something, like clockwork, or the Abbey, or even - gulp! - the Figure in Grey...</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]I've got these keys, what are they for?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Have you found anything you could unlock?</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>There are two things the keys will open for you.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Both are in the same room...</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>Go to the East Refectory.</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>You can open the clock and the garden door.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]What should I do with the clock?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Once you've got it open, you can reset it.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>...if you're brave enough, but once you start messing with clocks, there's no turning them back!</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>(Well, there is... but metaphorically there isn't. Never mind.)</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>If you're going to reset the clock, you'd better choose a sensible time. A time that will cause Calvin to leave his post, maybe!</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>Perhaps dinner time would be a good choice? Try setting the clock to that.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]What can I do in the garden?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>That metal hood looks interesting. There might be something underneath it, if you can figure out how the garden works.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Otherwise, the walls look interesting too. Might be a way out of the Abbey if you can get over them.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Have you seen anything that might help you get over a wall?</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>This one's up to you - but don't worry, if you can't solve it, you can still get out of the Abbey a different way!</hint>";
		say "			</topic>";
		say "		</hints>";
		select the main channel;
	if x is 3 and XML is in use:
		select the hints channel;
		say "		<hints title=[quotation mark]Chapter 3[quotation mark]>";
		say "			<topic title=[quotation mark]Where do I find the Archbishop?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Well, it's his Cathedral, so he could be anywhere.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>But most likely he'll be in his Library, at the north end above the Choir.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>If you can get through the door...</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]How do I avoid the monks?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>The monks are pretty engrossed in their chanting and prayers.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>In fact, they're so engrossed you can slip right past!</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>You might want to take a look at what's on the altar, however.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]There's a guard blocking my way![quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>His name is Doric and he works for the Swiss Watch. They can't be bribed and they never fall asleep on the job (or very rarely, anyway).</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Doric wants two things: written proof, and the Creed of the Church.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>You can also get him out of the way by annoying him.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>Try going to the north end of the Clerestory and throwing something at him.</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>Can you make it back round in time to beat him to the door?</hint>";
		say "				<hint id=[quotation mark]6[quotation mark]>No? Well, you'd better find that Creed and some written proof then!</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]What's the Creed of the Church?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Maybe you should know the Creed, Wren, but you don't seem to! You'll have to guess.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Lucky for you, in a world of clockwork people aren't always very imaginative.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>And they like to write everything down.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>Have you noticed the Great Seals on the floor of the Cathedral?</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>You can guess the Creed as many times as you like. If you get close, Doric will give you some hints.</hint>";
		say "				<hint id=[quotation mark]6[quotation mark]>If you're totally stuck, try just telling him the three items on the Seals.</hint>";
		say "				<hint id=[quotation mark]7[quotation mark]>The full creed is 'In the Name of the Lever, the Spring and the Winding Key'</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]How do I get a work order?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>You need to find one and pick it up. It's as simple as that.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Well, it's not quite that simple...</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>The work order belongs to strange Brother Sa'at, who works in the Orrey Room.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>But he'll let you have the work order once it's ready.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]Brother Sa'at wants a book. Where do I get it from?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>You get it from the Library, of course!</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>But the Library doesn't seem to have any shelves. It's got a contraption with cranks and numbers.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>The first thing you need to do is find the code for the book, by using the index.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>Try looking up the book in the card catalogue by the library door.</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>You'll need to remember what the books called!</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]How do I set the contraption to the right numbers?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>The machine has three cranks.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Cranks are good for turning.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>But you might have difficulty getting the numbers to move the way you want to. How to change the tens?</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>Read the description of turning the crank carefully.</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>You're always turning clockwise (like a good acolyte).</hint>";
		say "				<hint id=[quotation mark]6[quotation mark]>What happens if you turn the cranks anticlockwise?</hint>";
		say "				<hint id=[quotation mark]7[quotation mark]>Try turning the cranks clockwise and anticlockwise several times, until you get the numbers listed in the card catalogue.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]I've set the dials in the Library, but how do I get the book?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>You need to turn the machine on, of course!</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>There's a big chain. Pull!</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]What now? Brother Sa'at wants it stamped![quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>He needs to put his seal on it. A seal is a blob of molten wax into which a ring is pressed. It shows who sealed the letter, and that it hasnt been opened by anyone else.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Luckily, Sa'at will do all of that for you, so long as you can get him some wax.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Some purple wax, that is.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]Where do I get any wax around here?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>A Cathedral is full of wax.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>But it tends to be in a particular form.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Providing light...</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>There are some candles in the Shrine to the east of the Lower Nave. </hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>But candles are not quite waxy enough for Sa'at. You'll need to melt them down.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]I need to do some melting![quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Look around. Maybe you can find something hot.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>There's a brazier in the Calendar Shrine. Try melting the candles on that.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]Help! I can't get my wax back![quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>If you've melted some candles on the brazier, they'll have turned into pools of wax.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>But you need a tool to get them off the brazier again.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Have you found a good tool? You might have found one in the Abbey, or you might find one in the Library.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>Try scraping the wax with the knife.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]My wax is the wrong colour.[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>You need purple wax. The candles are red, yellow and blue.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>One candle won't be enough.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>You need a way of combining some colours.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>Try putting more than one candle on the brazier at the same time!</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>But which two colours will give you purple?</hint>";
		say "				<hint id=[quotation mark]6[quotation mark]>Keep trying combinations or if you get stuck...</hint>";
		say "				<hint id=[quotation mark]7[quotation mark]>Red and blue mix to make purple.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]What should I do with the Calendar Unlimited?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>You can look at it.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>You can be amazed at the power of good clockwork.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>You can even try standing on it.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>But in the end, it's not important to what you're doing here.</hint>";
		say "			</topic>";
		say "		</hints>";
		select the main channel;
	if x is 4 and XML is in use:
		select the hints channel;
		say "		<hints title=[quotation mark]Chapter 4[quotation mark]>";
		say "			<topic title=[quotation mark]The Bishop won't listen. He's thrown me out![quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>The Archbishop is a very important man.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>He's a big cog in the Klockwerk world.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>You are not important. You're a tiny tooth that only gets to intersect with other teeth once in every revolution.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>He won't listen to you. But that won't stop you getting into even worse trouble...</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]I've spotted the Figure! What can I do?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>You could try catching him.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Or maybe that's too scary.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>You could just hide and eavesdrop.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>Try listening.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]The Figure's gone![quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>You'd better get after him!</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Follow him around the clerestory, then up the secret ladder.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]How do I get off these gargoyles?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>You need to get over the clock.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>It's too far to jump.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>But there's something that can carry you over.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>Grab the penduluum.</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>But you'll have to time it right!</hint>";
		say "				<hint id=[quotation mark]6[quotation mark]>Wait, until the penduluum is in the right spot, then grab it.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]I'm stuck in the Lower Gears. Which way should I go?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>There are lots of different ways through the gears.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>You could get completely lost walking around them.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>But which way did the Figure actually go?</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>The Figure scurried away upwards.</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>Try examining the gears. There are rungs on them.</hint>";
		say "				<hint id=[quotation mark]6[quotation mark]>Go up (from anywhere in the Lower Gears!) and you'll be back on track.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]How do I use this barrel and chain?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>If you play around with the crank and the lever, you should be able to work out what it's for.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>The crank is for winding up the massive counterweight of the Cathedral Clock.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>It also winds the chain into the barrel and then, when the lever is released, that chain shoots away upwards.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>Upwards is the way you want to go.</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>Try winding the crank, taking hold of the chain, and then pulling the lever.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]Which way should I go?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>You're trying to keep on Figure's tail.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>If you're not sure which way to go, just try following him.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]Am I going to break my neck up here?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>It's pretty high up and you're doing some pretty dangerous things.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>But don't worry, it's just a game. You can't hurt yourself.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>And you can take your time - but you shouldn't, this is a chase!</hint>";
		say "			</topic>";
		say "		</hints>";
		select the main channel;
	if x is 5 and XML is in use:
		select the hints channel;
		say "		<hints title=[quotation mark]Chapter 5[quotation mark]>";
		say "			<topic title=[quotation mark]Help! I'm stuck on the Minute Hand![quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>No, you're not...</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Just you wait.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Or if you don't want to wait and you're brave, you could try jumping off.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]I don't know which way the Figure went![quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Keep following him.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>But once you're on the rooftops, he could have gone any way.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>You'll have to explore the area.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>You'll come across him - but you won't catch him quite yet!</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]The Figure got away! How do I go after him?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Seems impossible, doesn't it?</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>You'll need to explore around and see what you can find.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>That building opposite where the Figure's ornithopter was looks interesting, doesn't it?</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>Try getting across the alleyway.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]How do I get across the alleyway?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>It's too far to jump.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>You need to make a bridge.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>There's a pile of building debris on the roofs. See anything useful in it?</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>There's a long plank of wood. Try putting that in the notch.</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>Still no good? You need something to the weigh the wood down with.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]I need something heavy to help me.[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>You need something like a big pile of rocks.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Or bricks.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>There's a fallen-down chimney on the rooftops.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>Can you get some of the bricks free?</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>You might need a tool to cut away some of the mortar.</hint>";
		say "				<hint id=[quotation mark]6[quotation mark]>Use the knife again to cut the mortar.</hint>";
		say "				<hint id=[quotation mark]7[quotation mark]>Then take the pile of bricks and put it on the wooden board, to weigh it down.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]I can't get enough gas for the weather balloon![quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>No, you can't.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>You're going to need to find something else to float the balloon with.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Did you see anything on the rooftop that might help?</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>A source of hot air, perhaps?</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>There was a narrow chimney - but it's all the way across the alley.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]How do I get the steam where I need it to be?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>You need to connect up the chimney and the balloon.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Have you seen anything you could connect to the chimney?</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Have another look at the debris where you found the plank.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>There's a length of piping there.</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>Put the piping on the chimney.</hint>";
		say "				<hint id=[quotation mark]6[quotation mark]>But the pipe isn't pointing the right way.</hint>";
		say "				<hint id=[quotation mark]7[quotation mark]>Have you tried turning it?</hint>";
		say "				<hint id=[quotation mark]8[quotation mark]>You need to turn it so it points in the right direction, across the alleyway.</hint>";
		say "				<hint id=[quotation mark]9[quotation mark]>Try turning it to the southwest.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]This pipe's too hot to handle![quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>You need something to insulate it with.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Some kind of material.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Your rag is probably too small...</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>Try the Figure's tarpaulin sheet.</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>Wrap the sheet around the pipe. You should now be able to touch it safely.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]I'm all ready to take to the skies. But which way did the Figure go?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Hard to say. You need to see if you can spot him.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>He's a little far away now, so you need something to help you look.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Have you found the telescope?</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>Look through it. Can you see him that way?</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>Try turning the telescope to different directions.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]How do I get this telescope to move?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>There's a crank, and a pointer.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Did you try setting the pointer?</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>And then turning the crank?</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>If you did, then you should have got the telescope to move!</hint>";
		say "			</topic>";
		say "		</hints>";
		select the main channel;
	if x is 6 and XML is in use:
		select the hints channel;
		say "		<hints title=[quotation mark]Chapter 6[quotation mark]>";
		say "			<topic title=[quotation mark]Help, I'm going to be eaten![quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>This giant is seriously angry about his roof.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>You'd better explain yourself. Try telling him about what's happened to you.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Tell him about the Figure, for example, or tell him about the Abbot.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>You should find he's not quite as unfriendly as he first appears!</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]I need to find a diagram.[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>You need to search everywhere you can think of.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>There are a lot of places to look in Covalt's shop.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Try looking under things, inside things and on things.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>Examine everything!</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>For example, the desk is covered in lots of different things. Examine them all.</hint>";
		say "				<hint id=[quotation mark]6[quotation mark]>You can also ask Covalt about the various things.</hint>";
		say "				<hint id=[quotation mark]7[quotation mark]>If you really can't find the diagram...</hint>";
		say "				<hint id=[quotation mark]8[quotation mark]>...try looking under the bed.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]Covalt's thinking. What should I do?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Covalt's very clever, but sometimes clever people have too much going in their heads to find it all.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>You can help Covalt's thinking but only if you can work out what it is he's trying to think about.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Luckily, he's dropping a lot of clues.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>He wants to think of something different.</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>Have you tried asking him about different things?</hint>";
		say "				<hint id=[quotation mark]6[quotation mark]>Ask him about something different, literally!</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]I've got an address, what do I do?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Go!</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>There's a door to the street in the workshop. Go through it!</hint>";
		say "			</topic>";
		say "		</hints>";
		select the main channel;
	if x is 7 and XML is in use:
		select the hints channel;
		say "		<hints title=[quotation mark]Chapter 7[quotation mark]>";
		say "			<topic title=[quotation mark]I'm at the address but I can't get in![quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>There are guards blocking your way.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>You've got past guards before.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>You need to prove you're meant to be here.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>You've already done this once before.</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>Try showing them the work order that you showed to Doric.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]I'm inside the Counting House: where do I go?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Your aim is to get to the Difference Engine.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>It's a big machine that takes up most of the building.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>It's through the glass doors to the north...</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>...but you can't go that way, at least, not straight away - there are two women who'll catch you!</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>Maybe there's a way around the back.</hint>";
		say "				<hint id=[quotation mark]6[quotation mark]>Try going up the stairs and along the corridor.</hint>";
		say "				<hint id=[quotation mark]7[quotation mark]>You'll find a metal grille. Go through that.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]How can I get to the machine! I'll be spotted![quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Have you found your way to the balcony yet?</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>The two women talking are going to see you if you climb down.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>But they won't be there for very long.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>Wait until they've gone, then climb down.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]I can't set the abacus, it's locked![quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>You need a key.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Brother Horloge's keys aren't going to work. If you're going to find a key around here it'll be, well, around here.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Have a look around in the engine.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>Examine everything.</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>There's a ruby key sticking out of the spindles. Take that, and unlock the abacus with it.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]I can't figure out how to use this machine![quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>This machine takes questions in the form of five digit numbers, and then answers them.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>You need to set two questions: called the ACTOR and the ACTION.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>You can get a clue to phrase your questions by taking a pamphlet from the box by the giant lever.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>You need to ask where the Figure in Grey has gone. So the ACTOR should indicate the Figure, and the ACTION should indicate where he's going.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]The words on the Actor control seem wrong![quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>As you probably know, words can often have several meanings.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>The pamphlet lists their 'basic' meanings only.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>You'll have to use these as a guide and try to get as close to what you want as you can.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]What number should I use for the Actor?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Remember, you're trying to describe the Figure...</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Try to pick words that describe him.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>He's certainly powerful, wanting, and planning.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>The last two words are the hardest part.</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>Remember, you last saw him in an ornithopter. And the thing you know most about him is his colour...</hint>";
		say "				<hint id=[quotation mark]6[quotation mark]>The last two dials should be 'flying' and 'cloudy'.</hint>";
		say "				<hint id=[quotation mark]7[quotation mark]>So the number you want is 11336. Set the abacus to that.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]What number should I use for the Action?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>The question you're asking is where the Figure has gone.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Try to pick words that spell out something close to your question.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>The first word is easy. You want to know where he's going.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>The next few words should be easy to.</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>You want to know where in St Phillip the Figure is planning to go next.</hint>";
		say "				<hint id=[quotation mark]6[quotation mark]>So the number you want is 78325. Set the abacus to that.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]How do I turn the machine on?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>If you've got both numbers set...</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>...Then just pull the lever.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]Help! Someon's after me![quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>You'd better run!</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]I've been captured![quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>You're in trouble now.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>But if you're very lucky you'll still escape in one piece...</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Just wait to see what happens next, and don't panic!</hint>";
		say "			</topic>";
		say "		</hints>";
		select the main channel;
	if x is 8 and XML is in use:
		select the hints channel;
		say "		<hints title=[quotation mark]Chapter 8[quotation mark]>";
		say "			<topic title=[quotation mark]I'm at the Docks. Where do I go?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>The address was for a warehouse.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>You need to find a way into the warehouse.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>...but all the doors are locked. You'll need to find another way in.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]How do I get into the warehouse?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>The front door's locked.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>So is the door near the river.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Speaking of the river, have you noticed the bubbles coming up from underwater?</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>Might be something down there.</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>Try going for a swim.</hint>";
		say "				<hint id=[quotation mark]6[quotation mark]>Found the hatch?</hint>";
		say "				<hint id=[quotation mark]7[quotation mark]>You need to open the hatch and go inside.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]How do I turn these bolts?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>To turn a bolt, you need a wrench.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>A place like this might have tools lying around someplace.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Especially in piles of debris and rubble...</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>Go to the north side of the warehouse and search the rocks and water.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]I keep running out of air![quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>What would you do in real life?</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Go up for air, and then go back down again!</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]I'm stuck in a pipe. How do I get out?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Is there a grate above you?</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>There's a grate above you.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Go up.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]I'm inside the warehouse. What now?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Have you looked around?</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Okay, so there's not a lot to see.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>There is a door, however.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>The door with the iron ring attached to it.</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>Not only that, with the sign that says KEEP OUT.</hint>";
		say "				<hint id=[quotation mark]6[quotation mark]>You need to go that way.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]How do I get this door open?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>The door goes up.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>You n eed to lift it.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>It's far too heavy and it's bigger than you. </hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>You need to rig up some kind of machine.</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>Look around in the Loading Bay, see if you can find something helpful.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]I've got a rope. What do I do with it?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>You can tie it to things.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>You can loop it over things.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>So long as you can get up to anything worth looping over!</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>You can create some kind of pulley system.</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>And use it to open the door.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]Okay, I'm totally stuck here. How do I get this door open?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Get the ladder and the rope.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Tie the rope to the iron ring on the door.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Put the ladder against the first pipe, in the Storage area.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>Throw the rope over the pipe.</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>Then go to the Loading Bay.</hint>";
		say "				<hint id=[quotation mark]6[quotation mark]>Put the ladder against this pipe, and throw the rope over this pipe as well.</hint>";
		say "				<hint id=[quotation mark]7[quotation mark]>That's your pulley system set up. Now you need to pull the rope down and lift the door...</hint>";
		say "				<hint id=[quotation mark]8[quotation mark]>...Except it's too heavy. Can you think of a way to solve that problem?</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]How do I get enough weight on the rope?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Look around. Can you see anything heavy?</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>There's that crate, covered in iron chains.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>You can tie the rope to the crate.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>But the system is taut, it's not moving.</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>You need to move the crate. Downwards, if possible.</hint>";
		say "				<hint id=[quotation mark]6[quotation mark]>See the open drain?</hint>";
		say "				<hint id=[quotation mark]7[quotation mark]>Try pushing the crate into the drain. </hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]I'm through the door and now I'm in the dark.[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>There are some controls.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>You'll need to play around with them.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>The button doesn't seem to do anything. Try turning the bolt.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>You'll need to lift the lever and use the wrench to turn the bolt.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]There's a hissing noise. What do I do?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>You can turn the bolt again, but the hissing just goes away.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Get the hissing back. What else can you try?</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Try pressing the button..</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]There are stars! What now?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>The button doesn't do anything any more.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Try turning the bolt again.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]I don't understand the controls in the darkness![quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>There are two controls - a button, and a bolt.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>The bolt releases gas from lights on the wall.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>The button is an ignition.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>You need to release a little gas, fire the ignition, and then turn the gas up.</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>The lever is a safety mechanism (it doesn't do anything else.)</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]How do I get down?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>This is easy. You've got something to help you.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Something in the other room?</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Get the ladder and drop it.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]What do I do in the lower room?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>There's an army of statues.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Try examining them.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Try opening them.</hint>";
		say "			</topic>";
		say "		</hints>";
		select the main channel;
	if x is 9 and XML is in use:
		select the hints channel;
		say "		<hints title=[quotation mark]Chapter 9[quotation mark]>";
		say "			<topic title=[quotation mark]What should I tell Covalt?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Covalt's concerned about you, but he's also concerned about the Figure.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>You need to tell him about what you found in the warehouse.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>He'll mention what he thinks the Figure is after.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>Ask him about that.</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>He'll suggest an idea. Follow it up.</hint>";
		say "				<hint id=[quotation mark]6[quotation mark]>So, tell covalt about the warehouse, then ask him about the Perpetuum...</hint>";
		say "				<hint id=[quotation mark]7[quotation mark]>...and then ask him about his ideas for a trap, or for bait.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]Covalt has given me some coins. What do I do?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>You need to go and spend them.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Go out of the shop to the autopothecary across the street.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Go inside and buy a sleeping drug.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]How do I get ingredients?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>First, make sure you take a look at the price list.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>There's a slot for every ingredient. You've got coins.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Put a coin in the slot of the drug you want.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]Should I spend my third coin?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>That's up to you, young Wren.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]I've got my ingredients. What do I do with them?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>You need to use the press.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>It's got instructions on it.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Remember, a tincture is a liquid, so is an oil.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>Add the seeds if you bought them, then lift the lever, pour in the liquids and lift the lever again.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]I've got the drug. What now?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Well, you don't want to drink it!</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Go back and give it to Covalt.</hint>";
		say "			</topic>";
		say "		</hints>";
		select the main channel;
	if x is 10 and XML is in use:
		select the hints channel;
		say "		<hints title=[quotation mark]Chapter 10[quotation mark]>";
		say "			<topic title=[quotation mark]So where should I go?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>You need to get down into the crypt.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>You might have seen the entrance when you were here before.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>It's a dark grate...</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>...near the door to Sa'at's room.</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>Go to the East Apse.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]Help! Calvin and Drake![quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Stay hidden while they talk.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Once they've moved away, you'll be able to continue.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]The grate is locked![quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Well, what did you expect?</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>You need a key.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>There's a pretty strong clue in the text...</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>You need the Archbishop's key.</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>It's in his desk, in his Library.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]Help! Drake's blocking my way![quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Drake's standing right where Doric was before.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Drake is going to be a lot harder to shift.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>In fact, Drake's impossible to shift.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>You're going to have to find another way.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]Where there's a drill? Where is there a drill?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>You should get a reminder...</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>...about the secret passage from the choir to the Bishop's Library.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Go to the choir stalls and take a close look at them.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]The choir stalls are all in darkness.[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>You're going to need some light.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Have you seen somewhere in the Cathedral you could get a light?</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>You used them before...</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>Go back to the Shrine of the Saints and take a candle.</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>And it doesn't matter which colour!</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]I've got something to light, but how do I light it?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Stay in the Shrine.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>There's a lantern.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Light the candle on the lantern.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]What do I do with these choir stalls then?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Have you got enough light?</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Just examine them, or touch them.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Hey presto! A passage!</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]Help! I'm blocked by a clock![quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>You need to do the unthinkable.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>You need to stop that clock from working.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>There are lots of ways to do this.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>You could try jamming it with something.</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>Or you could try removing the weights.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]How do I open the desk?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>There's a catch.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>You need to slip it open.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Use something thin.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>Like the blottter, or the knife.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]Help! Where's the Perpetuum gone![quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Maybe it's been stolen.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Maybe Calvin found it.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Maybe the rats carried it away.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>Maybe you should try looking around.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]I've got the key, what now?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>You need to get into the crypt!</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>So what are you waiting for?</hint>";
		say "			</topic>";
		say "		</hints>";
		select the main channel;
	if x is 11 and XML is in use:
		select the hints channel;
		say "		<hints title=[quotation mark]Chapter 11[quotation mark]>";
		say "			<topic title=[quotation mark]I'm in the Crypt. Where do I go?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>One answer.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Down.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]The Stairs are too dark to go down![quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Your candle isn't good enough for a place this dark.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>You need something bigger and brighter.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>You'll need to make a torch.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]What should I be doing here?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>You need to look around.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>There's a room that's too dark to look around in.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>So you'd better make something to solve that.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>You need to make a torch.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]Okay, I know what I need to make. How do I do it?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>You need to make a torch.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>You're going to need a handle, and something to burn.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Look around in the Mortuary.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>You should find everything you need there.</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>Take one of the dowel rods and some linen cloth. Tie the cloth to the handle.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]I've built a torch but it burns up straight away![quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>The dry cloth burns too fast.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>You need to give it some fuel to burn off instead.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Take another look in the Mortuary.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>There's a bowl of oil.</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>Dip the cloth in the oil before you light it.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]I'm on the stair. What do I do?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>See the pedestal?</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>You need to fit something onto the top of it.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Take a look around upstairs.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>You need to take the sundial and attach it to the pedestal.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]I've built the pedestal. What now?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Have you tried turning it?</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>You'll need to put your torch somewhere first.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Put your torch in the sconce and turn the pedestal.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]What do I turn the pedestal to?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Try a few different times.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>The right time...</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>...is midnight.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]I'm at the bottom of the stairs. Where now?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Look around.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Examine the stones.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>See that door to the west? Go that way.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]How do I open the door?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Have you tried?</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>The Head is asking for a password.</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Can you think of one? You need to say it to the Head while it's awake.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>It's been clued a few times. If the Head goes to sleep, try opening the door again to make it wake up once more.</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>Otherwise, make some guesses and you should get some hints.</hint>";
		say "				<hint id=[quotation mark]6[quotation mark]>Are you really stuck, or just impatient?</hint>";
		say "				<hint id=[quotation mark]7[quotation mark]>The password is patience. Try saying it to the head.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]I'm in the Vault. What do I do?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>What you're here to do!</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Take the Perpetuum, and scram!</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]Help! I'm trapped![quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>You'd better try to hide!</hint>";
		say "			</topic>";
		say "		</hints>";
		select the main channel;
	if x is 12 and XML is in use:
		select the hints channel;
		say "		<hints title=[quotation mark]Chapter 12[quotation mark]>";
		say "			<topic title=[quotation mark]Covalt's in trouble! What do I do?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Go to the bedroom.</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>See anything that might distract the Figure?</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>Open the bird cage.</hint>";
		say "			</topic>";
		say "			<topic title=[quotation mark]I've got the Figure distracted. What now?[quotation mark]>";
		say "				<hint id=[quotation mark]1[quotation mark]>Can you see his weak spot?</hint>";
		say "				<hint id=[quotation mark]2[quotation mark]>Do you have anything that could jam his weak spot?</hint>";
		say "				<hint id=[quotation mark]3[quotation mark]>You need to put something into the slot on his neck.</hint>";
		say "				<hint id=[quotation mark]4[quotation mark]>Something you've had since the beginning....</hint>";
		say "				<hint id=[quotation mark]5[quotation mark]>Put your lucky clock key in the slot. Congratulations, you've saved Covalt and won the game!</hint>";
		say "			</topic>";
		say "		</hints>";
		select the main channel;

Shadow Hints ends here.
