packages:
  - packages/*
  - packages/extensions/testing
  - packages/extensions/basic-combat
  - '!packages/map-editor'
  - '!packages/cli'
  - '!packages/dev-tools'
  - stories/dungeo
  - stories/entropy
  - stories/channel-service-test
  - tutorials/familyzoo

ignoredBuiltDependencies:
  - electron

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - nx
