packages:
  - packages/*
  - packages/extensions/testing
  - '!packages/platforms'
  - '!packages/map-editor'
  - '!packages/cli'
  - '!packages/dev-tools'
  - '!packages/forge'
  - stories/dungeo

ignoredBuiltDependencies:
  - electron

onlyBuiltDependencies:
  - esbuild
  - nx
