packages:
  - packages/*
  - packages/extensions/testing
  - packages/extensions/basic-combat
  - '!packages/map-editor'
  - '!packages/interpreter'
  - stories/dungeo
  - stories/channel-service-test
  - tutorials/familyzoo
  - tools/shite

ignoredBuiltDependencies:
  - electron

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - nx
