sonar.cpd.exclusions=\
  **/tests/**,\
  **/*.test.ts,\
  **/*.spec.ts,\
  **/vitest.config.ts,\
  website/public/**,\
  templates/**,\
  packages/runtime/src/index.ts,\
  packages/bridge/src/index.ts

sonar.exclusions=\
  website/public/**
