/**
 * Version information for zifmia client
 * Auto-generated by build.sh - DO NOT EDIT
 */
export const CLIENT_VERSION = '0.9.92-beta';
export const BUILD_DATE = '2026-02-20T09:20:53Z';
export const ENGINE_VERSION = '0.9.92-beta';
export const VERSION_INFO = { version: CLIENT_VERSION, buildDate: BUILD_DATE, engineVersion: ENGINE_VERSION } as const;
