/**
 * character-manifest.ts — GENERATED by `repokit manifest` (ADR-310 Phase 3).
 * DO NOT EDIT — edit the world-model character-vocabulary / character
 * cognitive-presets sources and regenerate; the freshness gate
 * (`repokit manifest --check`, run by `repokit verify` and the platform
 * build) fails the build on drift.
 *
 * The descriptive character vocabulary the analyzer gates ADR-310 D2-D5/
 * D14 constructs against at compile time. Data only — chord stays
 * platform-FREE. These word lists are frozen author-facing compatibility
 * surface (freeze review: David, 2026-08-15 — docs/work/adr-310/
 * contracts.md §6): removing a word breaks stories, additions stay possible.
 *
 * Public interface: CHARACTER_MANIFEST, CharacterManifest.
 * Owner context: @sharpee/chord (generated artifact; browser-safe).
 */

export interface CharacterManifest {
  /** Personality adjectives (ADR-310 D2) — includes ADR-318 D8 conscience sensitivity. */
  personality: readonly string[];
  /** Intensity modifiers a personality adjective may carry (`very honest`). */
  intensities: readonly string[];
  /** Platform mood words (`mood nervous`, ADR-310 D3). */
  moods: readonly string[];
  /** Custom-mood nudge words (`define mood … like <mood>, but <modifier>`, ADR-310 D5). */
  moodModifiers: readonly string[];
  /** Disposition words (`feels wary of …`, ADR-310 D3) — some are two words. */
  dispositions: readonly string[];
  /** Threat words (runtime state; predicate vocabulary, never declared). */
  threats: readonly string[];
  /** Confidence words in ascending order (`knows`/`thinks` comma slot, ADR-310 D14). */
  confidences: readonly string[];
  /** Fact sources (`knows the murder, witnessed`, ADR-310 D3). */
  factSources: readonly string[];
  /** Belief resistance modes (ADR-310 D14 fold). */
  resistanceModes: readonly string[];
  /** Propagation audiences (`spreads … to <audience>`, ADR-310 D10). */
  audiences: readonly string[];
  /** Goal priorities (`goal <name>, <priority>`, ADR-310 D8). */
  goalPriorities: readonly string[];
  /** Influence modes (the `influence` header, ADR-310 D9). */
  influenceModes: readonly string[];
  /** Influence ranges (the `influence` header, ADR-310 D9). */
  influenceRanges: readonly string[];
  /** The five cognitive dimensions (kebab spelling) and their closed value sets (ADR-310 D4). */
  cognitiveDimensions: Readonly<Record<string, readonly string[]>>;
  /** Profile presets (ADR-310 D5 behavioral names) — preset name → dimension (kebab) → value. */
  profilePresets: Readonly<Record<string, Readonly<Record<string, string>>>>;
}

export const CHARACTER_MANIFEST: CharacterManifest = {
  personality: ["honest", "loyal", "cowardly", "paranoid", "cruel", "cunning", "curious", "stubborn", "generous", "vain", "devout", "impulsive", "remorseful", "untroubled"],
  intensities: ["slightly", "somewhat", "very", "extremely"],
  moods: ["calm", "content", "cheerful", "nervous", "anxious", "panicked", "angry", "furious", "sad", "grieving", "suspicious", "confused", "resigned"],
  moodModifiers: ["restless", "stiller", "darker", "brighter"],
  dispositions: ["despises", "hates", "dislikes", "wary of", "neutral", "likes", "trusts", "devoted to"],
  threats: ["safe", "uneasy", "wary", "threatened", "cornered", "desperate"],
  confidences: ["uncertain", "suspects", "believes", "certain"],
  factSources: ["witnessed", "told", "inferred", "assumed", "hallucinated"],
  resistanceModes: ["none", "reinterprets", "ignores"],
  audiences: ["trusted", "anyone", "allied"],
  goalPriorities: ["critical", "high", "medium", "low"],
  influenceModes: ["passive", "active"],
  influenceRanges: ["proximity", "targeted", "room"],
  cognitiveDimensions: {
    "perception": ["accurate", "filtered", "augmented"],
    "belief-formation": ["flexible", "rigid", "resistant"],
    "coherence": ["focused", "drifting", "fragmented"],
    "lucidity": ["stable", "fluctuating", "episodic"],
    "self-model": ["intact", "uncertain", "fractured"],
  },
  profilePresets: {
    "clear-headed": { "perception": "accurate", "belief-formation": "flexible", "coherence": "focused", "lucidity": "stable", "self-model": "intact" },
    "fixated": { "perception": "accurate", "belief-formation": "resistant", "coherence": "focused", "lucidity": "stable", "self-model": "intact" },
    "elsewhere": { "perception": "accurate", "belief-formation": "flexible", "coherence": "focused", "lucidity": "episodic", "self-model": "fractured" },
    "loosened": { "perception": "filtered", "belief-formation": "flexible", "coherence": "drifting", "lucidity": "fluctuating", "self-model": "intact" },
    "fogged": { "perception": "filtered", "belief-formation": "flexible", "coherence": "drifting", "lucidity": "fluctuating", "self-model": "uncertain" },
    "braced": { "perception": "filtered", "belief-formation": "rigid", "coherence": "drifting", "lucidity": "episodic", "self-model": "uncertain" },
    "unmoored": { "perception": "filtered", "belief-formation": "rigid", "coherence": "fragmented", "lucidity": "fluctuating", "self-model": "fractured" },
    "unquiet": { "perception": "augmented", "belief-formation": "resistant", "coherence": "fragmented", "lucidity": "episodic", "self-model": "uncertain" },
  },
};
