/**
 * stdlib-manifest.ts — GENERATED by `repokit manifest` (ADR-276 D2).
 * DO NOT EDIT — edit the stdlib source and regenerate; the freshness gate
 * (`repokit manifest --check`, run by `repokit verify` and the platform
 * build) fails the build on drift.
 *
 * The stdlib facts the analyzer gates against at compile time. Data only —
 * chord stays platform-FREE (imports nothing) while no longer being
 * stdlib-IGNORANT (ADR-276 D1). Locale-neutral facts sit at top level;
 * locale-owned facts (grammar shapes, direction words) go under `locales`,
 * keyed from day one (Q-2), `en-US` the sole entry.
 *
 * Public interface: STDLIB_MANIFEST, StdlibManifest, StdlibLocaleFacts.
 * Owner context: @sharpee/chord (generated artifact; browser-safe).
 */

/** Locale-owned stdlib facts (direction words join in a later ADR-276 phase). */
export interface StdlibLocaleFacts {
  /**
   * Standard grammar pattern shapes per action id — the loader's removable
   * surface (ADR-270 D3), rendered exactly as the registered rule patterns
   * (`take :item`); removal matching is string equality on these.
   */
  grammarShapes: Readonly<Record<string, readonly string[]>>;
}

export interface StdlibManifest {
  /** Full stdlib action-id set (`if.action.*`), from stdlib actions/constants.ts. */
  actionIds: ReadonlySet<string>;
  /**
   * Platform trait setting value types (trait adjective → key → type) —
   * the Q-3 declarative table from story-loader's setting-schema.ts.
   * Keyless v1 entity refs (`lockable with the iron key`) appear under
   * their message label (`key`/`tool`). Locale-neutral: platform facts.
   */
  settingSchema: Readonly<Record<string, Readonly<Record<string, 'boolean' | 'number' | 'entity-ref' | 'rooms'>>>>;
  /** The closed hiding-position domain (ratchet G3) — listing order is the message order. */
  hidingPositions: readonly string[];
  /** Locale-owned facts, keyed by locale id (ADR-276 Q-2). */
  locales: Readonly<Record<string, StdlibLocaleFacts>>;
}

export const STDLIB_MANIFEST: StdlibManifest = {
  actionIds: new Set([
    "if.action.about",
    "if.action.again",
    "if.action.answering",
    "if.action.asking",
    "if.action.attacking",
    "if.action.climbing",
    "if.action.closing",
    "if.action.consulting",
    "if.action.cutting",
    "if.action.digging",
    "if.action.drinking",
    "if.action.dropping",
    "if.action.eating",
    "if.action.emptying",
    "if.action.entering",
    "if.action.entering_room",
    "if.action.examining",
    "if.action.exiting",
    "if.action.giving",
    "if.action.going",
    "if.action.help",
    "if.action.hiding",
    "if.action.hints",
    "if.action.inserting",
    "if.action.inventory",
    "if.action.jumping",
    "if.action.kissing",
    "if.action.listening",
    "if.action.locking",
    "if.action.looking",
    "if.action.looking_behind",
    "if.action.looking_under",
    "if.action.lowering",
    "if.action.opening",
    "if.action.pulling",
    "if.action.pushing",
    "if.action.putting",
    "if.action.quitting",
    "if.action.raising",
    "if.action.reading",
    "if.action.removing",
    "if.action.restarting",
    "if.action.restoring",
    "if.action.revealing",
    "if.action.saving",
    "if.action.scoring",
    "if.action.searching",
    "if.action.setting",
    "if.action.showing",
    "if.action.sleeping",
    "if.action.smelling",
    "if.action.switching_off",
    "if.action.switching_on",
    "if.action.taking",
    "if.action.taking_off",
    "if.action.talking",
    "if.action.tasting",
    "if.action.telling",
    "if.action.throwing",
    "if.action.touching",
    "if.action.turning",
    "if.action.undoing",
    "if.action.unlocking",
    "if.action.using",
    "if.action.verifying",
    "if.action.version",
    "if.action.waiting",
    "if.action.waking",
    "if.action.waving",
    "if.action.wearing",
  ]),
  settingSchema: {
    "combatant": { "health": "number", "max-health": "number", "skill": "number", "base-damage": "number", "armor": "number", "attack-power": "number", "defense": "number", "experience-value": "number", "hostile": "boolean", "can-retaliate": "boolean", "drops-inventory": "boolean", "is-undead": "boolean" },
    "weapon": { "damage": "number", "skill-bonus": "number", "is-blessed": "boolean", "glows-near-danger": "boolean" },
    "guard": { "can-move": "boolean", "announces-movement": "boolean", "allowed-rooms": "rooms", "forbidden-rooms": "rooms" },
    "passive": { "can-move": "boolean", "announces-movement": "boolean", "allowed-rooms": "rooms", "forbidden-rooms": "rooms" },
    "wanderer": { "can-move": "boolean", "announces-movement": "boolean", "allowed-rooms": "rooms", "forbidden-rooms": "rooms", "move-chance": "number" },
    "follower": { "can-move": "boolean", "announces-movement": "boolean", "allowed-rooms": "rooms", "forbidden-rooms": "rooms", "immediate": "boolean" },
    "patrol": { "can-move": "boolean", "announces-movement": "boolean", "allowed-rooms": "rooms", "forbidden-rooms": "rooms", "route": "rooms", "loop": "boolean", "wait-turns": "number" },
    "openable": { "tool": "entity-ref" },
    "lockable": { "key": "entity-ref" },
    "cuttable": { "tool": "entity-ref" },
    "diggable": { "tool": "entity-ref" },
  },
  hidingPositions: ["behind", "under", "on", "inside"],
  locales: {
    'en-US': {
      grammarShapes: {
        "if.action.about": ["about", "info", "credits"],
        "if.action.again": ["again", "g"],
        "if.action.asking": ["ask :recipient about :topic", "question :recipient about :topic", "inquire of :recipient about :topic"],
        "if.action.attacking": ["attack :target", "kill :target", "fight :target", "slay :target", "murder :target", "hit :target", "strike :target", "break :target", "smash :target", "destroy :target", "attack :target with|using :weapon", "kill :target with|using :weapon", "hit :target with|using :weapon", "strike :target with|using :weapon"],
        "if.action.climbing": ["climb :target", "climb up :target", "climb down :target", "scale :target", "ascend :target", "descend :target"],
        "if.action.closing": ["close :door", "shut :door", "cover :door"],
        "if.action.cutting": ["cut :object with|using :tool", "cut :target", "slice :target", "chop :target"],
        "if.action.digging": ["dig :location with|using :tool", "dig :target"],
        "if.action.drinking": ["drink :item", "sip :item", "quaff :item", "swallow :item", "imbibe :item", "drink from :target", "sip from :target"],
        "if.action.dropping": ["drop :item", "discard :item", "release :item", "put down :item", "throw away :item", "let go of :item"],
        "if.action.eating": ["eat :item", "consume :item", "devour :item", "munch :item", "nibble :item", "munch on :item", "nibble on :item"],
        "if.action.entering": ["enter :portal", "get in :portal", "get into :portal", "climb in :portal", "climb into :portal", "go in :portal", "go into :portal", "board :vehicle", "get on :vehicle"],
        "if.action.examining": ["examine :target", "x :target", "inspect :target", "check :target", "view :target", "observe :target", "look at :target", "look [carefully] at :target"],
        "if.action.exiting": ["go out", "exit", "get out", "leave", "climb out", "exit :container", "get out of :container", "climb out of :container", "disembark", "disembark :vehicle", "get off :vehicle", "alight"],
        "if.action.giving": ["give :item to :recipient", "give :recipient :item", "offer :item to :recipient", "hand :item to :recipient", "hand :recipient :item"],
        "if.action.going": ["go north", "go n", "walk north", "walk n", "run north", "run n", "head north", "head n", "travel north", "travel n", "north", "n", "go south", "go s", "walk south", "walk s", "run south", "run s", "head south", "head s", "travel south", "travel s", "south", "s", "go east", "go e", "walk east", "walk e", "run east", "run e", "head east", "head e", "travel east", "travel e", "east", "e", "go west", "go w", "walk west", "walk w", "run west", "run w", "head west", "head w", "travel west", "travel w", "west", "w", "go northeast", "go ne", "walk northeast", "walk ne", "run northeast", "run ne", "head northeast", "head ne", "travel northeast", "travel ne", "northeast", "ne", "go northwest", "go nw", "walk northwest", "walk nw", "run northwest", "run nw", "head northwest", "head nw", "travel northwest", "travel nw", "northwest", "nw", "go southeast", "go se", "walk southeast", "walk se", "run southeast", "run se", "head southeast", "head se", "travel southeast", "travel se", "southeast", "se", "go southwest", "go sw", "walk southwest", "walk sw", "run southwest", "run sw", "head southwest", "head sw", "travel southwest", "travel sw", "southwest", "sw", "go up", "go u", "walk up", "walk u", "run up", "run u", "head up", "head u", "travel up", "travel u", "up", "u", "go down", "go d", "walk down", "walk d", "run down", "run d", "head down", "head d", "travel down", "travel d", "down", "d", "go in", "go inside", "walk in", "walk inside", "run in", "run inside", "head in", "head inside", "travel in", "travel inside", "in", "inside", "go out", "go outside", "walk out", "walk outside", "run out", "run outside", "head out", "head outside", "travel out", "travel outside", "out", "outside"],
        "if.action.help": ["help", "commands"],
        "if.action.hiding": ["hide behind :target", "duck behind :target", "crouch behind :target", "hide under :target", "duck under :target", "crouch under :target", "hide on :target", "hide in :target", "hide inside :target", "duck inside :target"],
        "if.action.inserting": ["put :item in|into|inside :container", "insert :item in|into :container"],
        "if.action.inventory": ["inventory", "inv", "i"],
        "if.action.listening": ["hear", "hear :target", "listen", "listen to :target"],
        "if.action.locking": ["lock :target", "lock :target with|using :key", "secure :target"],
        "if.action.looking": ["look", "l", "look [around]"],
        "if.action.lowering": ["lower :target"],
        "if.action.opening": ["open :door", "open :container with|using :tool", "unwrap :door", "uncover :door", "open up :door"],
        "if.action.pulling": ["pull :target", "drag :target", "yank :target", "tug :target"],
        "if.action.pushing": ["push :target", "press :target", "shove :target", "move :target", "move :target north", "move :target n", "move :target south", "move :target s", "move :target east", "move :target e", "move :target west", "move :target w", "move :target northeast", "move :target ne", "move :target northwest", "move :target nw", "move :target southeast", "move :target se", "move :target southwest", "move :target sw", "move :target up", "move :target u", "move :target down", "move :target d", "move :target in", "move :target inside", "move :target out", "move :target outside"],
        "if.action.putting": ["put :item on|onto :supporter", "hang :item on :hook", "move :item to :destination", "place :item in|into|inside :container", "place :item on|onto :supporter"],
        "if.action.quitting": ["quit", "q", "exit game"],
        "if.action.raising": ["raise :target", "lift :target"],
        "if.action.reading": ["read :target", "peruse :target", "study :target"],
        "if.action.removing": ["take :item from :container", "get :item from :container", "take :item from :container with|using :tool", "remove :item from :container", "extract :item from :container"],
        "if.action.restarting": ["restart"],
        "if.action.restoring": ["restore", "load", "load game", "restore game"],
        "if.action.revealing": ["stand up", "come out", "reveal myself", "unhide", "stop hiding"],
        "if.action.saving": ["save", "save game"],
        "if.action.scoring": ["score", "points"],
        "if.action.searching": ["search [carefully]", "search :target", "look in|inside :target", "look through :target", "rummage in|through :target"],
        "if.action.showing": ["show :item to :recipient", "show :recipient :item", "display :item to :recipient", "present :item to :recipient"],
        "if.action.sleeping": ["sleep", "nap", "doze", "rest", "slumber"],
        "if.action.smelling": ["smell", "sniff", "smell :target", "sniff :target"],
        "if.action.switching_off": ["turn off :device", "switch off :device", "flip off :device", "turn :device off", "deactivate :device", "stop :device", "power off :device"],
        "if.action.switching_on": ["turn on :device", "switch on :device", "flip on :device", "turn :device on", "activate :device", "start :device", "power on :device"],
        "if.action.taking": ["take :item", "get :item", "grab :item", "acquire :item", "collect :item", "pick up :item", "take up :item"],
        "if.action.taking_off": ["remove :item", "doff :item", "unequip :item", "take off :item", "take :item off"],
        "if.action.talking": ["talk to|with :target", "speak to|with :target", "chat with :target", "converse with :target", "tell me more", "continue", "go on"],
        "if.action.telling": ["tell :recipient about :topic", "inform :recipient about :topic"],
        "if.action.throwing": ["throw :item at :target", "throw :item", "toss :item", "hurl :item", "throw :item to :recipient", "toss :item at :target", "toss :item to :recipient", "hurl :item at :target", "hurl :item to :recipient"],
        "if.action.touching": ["touch :target", "rub :target", "feel :target", "pat :target", "stroke :target", "poke :target", "prod :target"],
        "if.action.turning": ["turn :target", "rotate :target", "twist :target"],
        "if.action.undoing": ["undo"],
        "if.action.unlocking": ["unlock :door with|using :key", "unlock :target", "unsecure :target"],
        "if.action.version": ["version"],
        "if.action.waiting": ["wait", "z"],
        "if.action.wearing": ["wear :item", "don :item", "equip :item", "put on :item"],
      },
    },
  },
};
