/**
 * stdlib-manifest.ts — GENERATED by `repokit manifest` (ADR-276 D2).
 * DO NOT EDIT — edit the stdlib source and regenerate; the freshness gate
 * (`repokit manifest --check`, run by `repokit verify` and the platform
 * build) fails the build on drift.
 *
 * The stdlib facts the analyzer gates against at compile time. Data only —
 * chord stays platform-FREE (imports nothing) while no longer being
 * stdlib-IGNORANT (ADR-276 D1). Locale-neutral facts sit at top level;
 * locale-owned facts (grammar shapes, direction words) go under `locales`,
 * keyed from day one (Q-2), `en-US` the sole entry.
 *
 * Public interface: STDLIB_MANIFEST, StdlibManifest, StdlibLocaleFacts.
 * Owner context: @sharpee/chord (generated artifact; browser-safe).
 */

/** Locale-owned stdlib facts — filled by later ADR-276 phases (grammar shapes, direction words). */
export interface StdlibLocaleFacts {}

export interface StdlibManifest {
  /** Full stdlib action-id set (`if.action.*`), from stdlib actions/constants.ts. */
  actionIds: ReadonlySet<string>;
  /** Locale-owned facts, keyed by locale id (ADR-276 Q-2). */
  locales: Readonly<Record<string, StdlibLocaleFacts>>;
}

export const STDLIB_MANIFEST: StdlibManifest = {
  actionIds: new Set([
    "if.action.about",
    "if.action.again",
    "if.action.answering",
    "if.action.asking",
    "if.action.attacking",
    "if.action.climbing",
    "if.action.closing",
    "if.action.consulting",
    "if.action.cutting",
    "if.action.digging",
    "if.action.drinking",
    "if.action.dropping",
    "if.action.eating",
    "if.action.emptying",
    "if.action.entering",
    "if.action.entering_room",
    "if.action.examining",
    "if.action.exiting",
    "if.action.giving",
    "if.action.going",
    "if.action.help",
    "if.action.hiding",
    "if.action.hints",
    "if.action.inserting",
    "if.action.inventory",
    "if.action.jumping",
    "if.action.kissing",
    "if.action.listening",
    "if.action.locking",
    "if.action.looking",
    "if.action.looking_behind",
    "if.action.looking_under",
    "if.action.lowering",
    "if.action.opening",
    "if.action.pulling",
    "if.action.pushing",
    "if.action.putting",
    "if.action.quitting",
    "if.action.raising",
    "if.action.reading",
    "if.action.removing",
    "if.action.restarting",
    "if.action.restoring",
    "if.action.revealing",
    "if.action.saving",
    "if.action.scoring",
    "if.action.searching",
    "if.action.setting",
    "if.action.showing",
    "if.action.sleeping",
    "if.action.smelling",
    "if.action.switching_off",
    "if.action.switching_on",
    "if.action.taking",
    "if.action.taking_off",
    "if.action.talking",
    "if.action.tasting",
    "if.action.telling",
    "if.action.throwing",
    "if.action.touching",
    "if.action.turning",
    "if.action.undoing",
    "if.action.unlocking",
    "if.action.using",
    "if.action.verifying",
    "if.action.version",
    "if.action.waiting",
    "if.action.waking",
    "if.action.waving",
    "if.action.wearing",
  ]),
  locales: { 'en-US': {} },
};
