/**
 * build.ts — `devkit build`: the full platform+story build pipeline (build.sh
 * update_versions + build_platform + generate_genai_api + build_story + build_bundle).
 * devkit orchestrates; tsf/pnpm compile.
 *
 * Owner context: @sharpee/devkit (ADR-180 Phase 3). Output must match build.sh
 * byte-for-byte (frozen version+date) until build.sh is retired at cutover.
 *
 * Public interface: runBuild(opts). Sub-steps stampVersions/buildPlatform/
 * generateGenaiApi/buildStory are exported for the parity harness + tests.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import {
  PLATFORM_PACKAGES,
  findRepoRoot,
  resolveStoryDir,
  storyVersionFile,
  tsfBin,
} from '../repo';
import { runBundle } from './bundle';
import { buildBrowserClient } from './browser';
import { buildZifmiaServer } from './zifmia';

/**
 * The generator name written into stamped version.ts files. build.sh was retired at
 * the ADR-180 Phase 3d cutover (parity verified byte-identical first), so devkit now
 * names itself as the generator.
 */
const GENERATOR = 'devkit';

export interface BuildOptions {
  root?: string;
  /** Story name to build (resolved stories/<name> then tutorials/<name>). */
  story?: string;
  /** Resume the platform build from this package short-name (build.sh --skip). */
  skipTo?: string;
  /** Explicit version to stamp (else read packages/sharpee/package.json). */
  version?: string;
  /** Frozen build date (parity determinism). Defaults to now in build.sh's format. */
  buildDate?: string;
  /** Skip version stamping (build.sh --no-version). */
  noVersion?: boolean;
  /** Skip genai-api generation. */
  noGenai?: boolean;
  /** Run the ESM build pass (needed for browser/story-bundle targets; false for the CLI bundle). */
  esm?: boolean;
  /** Run the bundle step at the end (default true — the full build.sh pipeline). */
  bundle?: boolean;
  /** Also build the browser client (dist/web/<story>/). Implies --esm; requires a story. */
  browser?: boolean;
  /** Also build the zifmia multi-user server (tools/zifmia/dist/). Implies --esm. */
  zifmia?: boolean;
  quiet?: boolean;
}

function nowStamp(): string {
  return new Date().toISOString().replace(/\.\d{3}Z$/, 'Z');
}

/** Rewrite a package.json's version, preserving key order + 2-space indent + trailing newline. */
function writePkgVersion(pkgPath: string, version: string): void {
  const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
  pkg.version = version;
  writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
}

/**
 * Stamp versions (build.sh update_versions, CLI/story scope). Returns the resolved
 * SHARPEE_VERSION so callers can log it. See module-level Behavior Statement.
 */
export function stampVersions(root: string, opts: BuildOptions): string {
  const sharpeePkg = join(root, 'packages', 'sharpee', 'package.json');
  const sharpeeVersion = opts.version ?? JSON.parse(readFileSync(sharpeePkg, 'utf8')).version;
  if (opts.noVersion) return sharpeeVersion;

  const buildDate = opts.buildDate ?? nowStamp();

  if (existsSync(sharpeePkg)) writePkgVersion(sharpeePkg, sharpeeVersion);

  // Story version.ts — stories/<name> only (build.sh hardcodes stories/, tutorials are not stamped).
  if (opts.story) {
    const storyPkg = join(root, 'stories', opts.story, 'package.json');
    if (existsSync(storyPkg)) {
      const storyVer = JSON.parse(readFileSync(storyPkg, 'utf8')).version;
      const versionFile = storyVersionFile(root, opts.story);
      mkdirSync(dirname(versionFile), { recursive: true });
      writeFileSync(
        versionFile,
        `/**
 * Version information for ${opts.story}
 * Auto-generated by ${GENERATOR} - DO NOT EDIT
 */
export const STORY_VERSION = '${storyVer}';
export const BUILD_DATE = '${buildDate}';
export const ENGINE_VERSION = '${sharpeeVersion}';
export const VERSION_INFO = { version: STORY_VERSION, buildDate: BUILD_DATE, engineVersion: ENGINE_VERSION } as const;
`,
      );
    }
  }

  // zifmia package.json version (build.sh update_versions stamps it for -c zifmia).
  if (opts.zifmia) {
    const zifmiaPkg = join(root, 'tools', 'zifmia', 'package.json');
    if (existsSync(zifmiaPkg)) writePkgVersion(zifmiaPkg, sharpeeVersion);
  }
  return sharpeeVersion;
}

/** Build all platform packages in dependency order (build.sh build_platform). */
export function buildPlatform(root: string, opts: BuildOptions): void {
  const run = (pkg: string, args: string[]) =>
    execFileSync(pkg, args, { cwd: root, stdio: opts.quiet ? 'ignore' : 'inherit' });

  let skipping = Boolean(opts.skipTo);
  for (const [pkg, dir] of PLATFORM_PACKAGES) {
    if (skipping) {
      if (dir === opts.skipTo) skipping = false;
      else continue;
    }
    run('pnpm', ['--filter', pkg, 'build']);
    // Invariant: assert the compile produced output (precludes the .tsbuildinfo silent no-op class).
    const distIndex = join(root, 'packages', dir, 'dist', 'index.js');
    if (!existsSync(distIndex)) {
      throw new Error(`build of ${pkg} produced no dist/index.js (silent no-op?) at ${distIndex}`);
    }
  }

  if (opts.esm) {
    let esmSkip = Boolean(opts.skipTo);
    for (const [pkg, dir] of PLATFORM_PACKAGES) {
      if (esmSkip) {
        if (dir === opts.skipTo) esmSkip = false;
        else continue;
      }
      if (existsSync(join(root, 'packages', dir, 'tsconfig.esm.json'))) {
        // tsf drives the esm target so esmExtensions post-processing runs (build.sh comment 555-557).
        run(tsfBin(root), ['build', '--condition', 'esm', '--filter', pkg]);
      }
    }
  }
}

/** Generate the genai-api reference (build.sh generate_genai_api). */
export function generateGenaiApi(root: string, opts: BuildOptions): void {
  execFileSync('node', ['scripts/generate-genai-api.js'], {
    cwd: root,
    stdio: opts.quiet ? 'ignore' : 'inherit',
  });
}

/** Build a story package (build.sh build_story + resolve_story_pkg). */
export function buildStory(root: string, story: string, opts: BuildOptions): void {
  const dir = resolveStoryDir(root, story);
  if (!dir) throw new Error(`story not found: ${story} (looked in stories/ and tutorials/)`);
  const pkg = dir.includes('/tutorials/') ? `@sharpee/tutorial-${story}` : `@sharpee/story-${story}`;
  execFileSync('pnpm', ['--filter', pkg, 'build'], {
    cwd: root,
    stdio: opts.quiet ? 'ignore' : 'inherit',
  });
  if (opts.esm && existsSync(join(dir, 'tsconfig.esm.json'))) {
    execFileSync(tsfBin(root), ['build', '--condition', 'esm', '--filter', pkg], {
      cwd: root,
      stdio: opts.quiet ? 'ignore' : 'inherit',
    });
  }
}

/** Run the full build pipeline. */
export function runBuild(opts: BuildOptions = {}): void {
  const root = opts.root ?? findRepoRoot();
  const log = (m: string) => !opts.quiet && console.log(m);

  // Client targets (browser/zifmia) need the ESM build pass (build.sh runs it when a client is requested).
  const effective: BuildOptions = opts.browser || opts.zifmia ? { ...opts, esm: true } : opts;
  if (effective.browser && !effective.story) throw new Error('--browser requires a story');

  log('=== devkit build ===');
  const version = stampVersions(root, effective);
  log(`version: ${version}${effective.story ? ` · story: ${effective.story}` : ''}`);
  buildPlatform(root, effective);
  if (!effective.noGenai) generateGenaiApi(root, effective);
  if (effective.story) buildStory(root, effective.story, effective);
  if (effective.bundle !== false) runBundle({ root, quiet: effective.quiet });
  if (effective.browser) buildBrowserClient(root, effective.story!, { quiet: effective.quiet });
  if (effective.zifmia) buildZifmiaServer(root, { quiet: effective.quiet });
  log('=== build complete ===');
}
