/**
 * build.test.ts — unit tests for version stamping + repo helpers (ADR-180 Phase 3).
 * Derived from the stampVersions Behavior Statement. The byte-for-byte parity with
 * build.sh's full build is covered by scripts/parity-cli-bundle.sh.
 */
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { stampVersions } from './build';
import { findRepoRoot, resolveStoryDir } from '../repo';

describe('stampVersions', () => {
  let root: string;

  const writeJson = (p: string, obj: unknown) => {
    mkdirSync(join(root, p, '..'), { recursive: true });
    writeFileSync(join(root, p), JSON.stringify(obj, null, 2) + '\n');
  };

  beforeEach(() => {
    root = mkdtempSync(join(tmpdir(), 'devkit-build-'));
    mkdirSync(join(root, 'packages', 'sharpee'), { recursive: true });
    writeJson('packages/sharpee/package.json', { name: '@sharpee/sharpee', version: '0.9.113' });
    mkdirSync(join(root, 'stories', 'dungeo', 'src'), { recursive: true });
    writeJson('stories/dungeo/package.json', { name: '@sharpee/story-dungeo', version: '1.0.0' });
  });

  afterEach(() => rmSync(root, { recursive: true, force: true }));

  it('writes version.ts in the stable format, with frozen date', () => {
    stampVersions(root, { story: 'dungeo', version: '0.9.113', buildDate: '2026-05-12T21:38:50Z' });
    const expected = `/**
 * Version information for dungeo
 * Auto-generated by devkit - DO NOT EDIT
 */
export const STORY_VERSION = '1.0.0';
export const BUILD_DATE = '2026-05-12T21:38:50Z';
export const ENGINE_VERSION = '0.9.113';
export const VERSION_INFO = { version: STORY_VERSION, buildDate: BUILD_DATE, engineVersion: ENGINE_VERSION } as const;
`;
    expect(readFileSync(join(root, 'stories/dungeo/src/version.ts'), 'utf8')).toBe(expected);
  });

  it('stamps the sharpee package.json version (override wins)', () => {
    stampVersions(root, { version: '9.9.9-test', buildDate: '2026-01-01T00:00:00Z' });
    const pkg = JSON.parse(readFileSync(join(root, 'packages/sharpee/package.json'), 'utf8'));
    expect(pkg.version).toBe('9.9.9-test');
  });

  it('does NOT stamp tutorials stories (build.sh hardcodes stories/)', () => {
    mkdirSync(join(root, 'tutorials', 'familyzoo', 'src'), { recursive: true });
    writeJson('tutorials/familyzoo/package.json', { name: '@sharpee/tutorial-familyzoo', version: '2.0.0' });
    stampVersions(root, { story: 'familyzoo', version: '0.9.113', buildDate: '2026-01-01T00:00:00Z' });
    // No stories/familyzoo → no version.ts written under tutorials.
    expect(() => readFileSync(join(root, 'tutorials/familyzoo/src/version.ts'), 'utf8')).toThrow();
  });

  it('--no-version returns the version without writing version.ts', () => {
    const v = stampVersions(root, { story: 'dungeo', noVersion: true });
    expect(v).toBe('0.9.113');
    expect(() => readFileSync(join(root, 'stories/dungeo/src/version.ts'), 'utf8')).toThrow();
  });
});

describe('repo helpers', () => {
  it('findRepoRoot walks up to the pnpm-workspace.yaml', () => {
    const root = mkdtempSync(join(tmpdir(), 'devkit-root-'));
    writeFileSync(join(root, 'pnpm-workspace.yaml'), 'packages:\n');
    const nested = join(root, 'packages', 'x', 'src');
    mkdirSync(nested, { recursive: true });
    expect(findRepoRoot(nested)).toBe(root);
    rmSync(root, { recursive: true, force: true });
  });

  it('resolveStoryDir prefers stories/ then tutorials/', () => {
    const root = mkdtempSync(join(tmpdir(), 'devkit-story-'));
    mkdirSync(join(root, 'tutorials', 'fz'), { recursive: true });
    expect(resolveStoryDir(root, 'fz')).toBe(join(root, 'tutorials', 'fz'));
    expect(resolveStoryDir(root, 'nope')).toBeNull();
    rmSync(root, { recursive: true, force: true });
  });
});
