/**
 * Version information for dungeo
 * Auto-generated by devkit - DO NOT EDIT
 */
export const STORY_VERSION = '1.0.8';
export const BUILD_DATE = '2026-06-22T07:24:12Z';
export const ENGINE_VERSION = '1.0.8';
export const VERSION_INFO = { version: STORY_VERSION, buildDate: BUILD_DATE, engineVersion: ENGINE_VERSION } as const;
