/**
 * Version information for Dungeo
 *
 * This file is auto-generated by the bundle script.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 */

/** Story version (auto-incremented on bundle) */
export const STORY_VERSION = '1.0.0-alpha.6';

/** Build timestamp (ISO 8601) */
export const BUILD_DATE = '2026-01-19T02:15:57Z';

/** Engine version at build time */
export const ENGINE_VERSION = '0.9.3-beta.1';

/** Combined version info object for easy access */
export const VERSION_INFO = {
  version: STORY_VERSION,
  buildDate: BUILD_DATE,
  engineVersion: ENGINE_VERSION
} as const;
