/**
 * Version information for cloak-of-darkness
 * Auto-generated by devkit - DO NOT EDIT
 */
export const STORY_VERSION = '0.9.79-beta';
export const BUILD_DATE = '2026-07-11T02:20:30Z';
export const ENGINE_VERSION = '2.2.0';
export const VERSION_INFO = { version: STORY_VERSION, buildDate: BUILD_DATE, engineVersion: ENGINE_VERSION } as const;
