/**
 * POST /api/identities — create a new persistent identity (ADR-161).
 *
 * Public interface: {@link registerCreateIdentityRoute}, {@link CreateIdentityDeps}.
 * Wire types (`CreateIdentityRequest`, `CreateIdentityResponse`) live in
 * `../../wire/http-api.ts` — shared with the browser client.
 *
 * Bounded context: HTTP layer (ADR-161 Decision: Identity lifecycle / Create).
 *
 * Generates `(id, passcode)` server-side, hashes the passcode with argon2id,
 * persists `(id, handle, passcode_hash)`, and returns `(id, handle, passcode)`
 * to the caller. The plaintext passcode is returned exactly once; the server
 * cannot recover it later. Cross-device portability is via download/upload
 * CSV (Phase C), not by re-fetching the passcode.
 *
 * Handle constraints (ADR-161, Resolved Choice #4 default = 3):
 *   - 3–12 characters
 *   - alpha only: `[A-Za-z]+` (no digits, underscores, hyphens, spaces)
 *   - case preserved for display; uniqueness is case-insensitive
 *
 * Id is generated by the repository's Crockford-32 generator with a
 * collision-retry budget (~1.1T-combination space; effectively unreachable).
 *
 * Passcode is generated from the EFF Large Wordlist as `<word>-<word>`.
 */

import type { Hono, MiddlewareHandler } from 'hono';
import type { IdentitiesRepository } from '../../repositories/identities.js';
import type { HashService } from '../../auth/hash-service.js';
import { HttpError } from '../middleware/error-envelope.js';
import { generatePasscode } from '../../identity/passcode-generator.js';
import type { CreateIdentityResponse } from '../../wire/http-api.js';

export interface CreateIdentityDeps {
  identities: IdentitiesRepository;
  hashService: HashService;
  /**
   * Optional rate-limit middleware. When supplied, it fronts the route. Tests
   * that don't exercise rate limiting omit it.
   */
  rateLimit?: MiddlewareHandler;
}

interface CreateIdentityBody {
  handle?: unknown;
}

const HANDLE_PATTERN = /^[A-Za-z]+$/;
const HANDLE_MIN = 3;
const HANDLE_MAX = 12;

/**
 * Pass-through middleware used when no rate-limiter is supplied. Lets the
 * route's signature stay uniform whether or not the limiter is wired in.
 */
const passthrough: MiddlewareHandler = async (_c, next) => {
  await next();
};

export function registerCreateIdentityRoute(app: Hono, deps: CreateIdentityDeps): void {
  app.post('/api/identities', deps.rateLimit ?? passthrough, async (c) => {
    const body = (await c.req.json().catch(() => null)) as CreateIdentityBody | null;
    if (!body) throw new HttpError(400, 'bad_request', 'JSON body required');

    const handle = typeof body.handle === 'string' ? body.handle : '';
    if (!handle) throw new HttpError(400, 'missing_field', 'handle is required');
    if (handle.length < HANDLE_MIN || handle.length > HANDLE_MAX) {
      throw new HttpError(
        400,
        'invalid_handle',
        `handle must be ${HANDLE_MIN}–${HANDLE_MAX} characters`,
      );
    }
    if (!HANDLE_PATTERN.test(handle)) {
      throw new HttpError(
        400,
        'invalid_handle',
        'handle must be letters only (no digits, underscores, hyphens, or spaces)',
      );
    }

    // Pre-check uniqueness so the common-case error returns 409 with a clean
    // detail. The DB UNIQUE index is the source of truth — a race between two
    // concurrent creates falls back to the catch below.
    if (deps.identities.findByHandle(handle)) {
      throw new HttpError(409, 'handle_taken', 'that handle is already in use');
    }

    const passcode = generatePasscode();
    const passcode_hash = await deps.hashService.hash(passcode);

    let identity;
    try {
      identity = deps.identities.create({ handle, passcode_hash });
    } catch (err) {
      // Race fallback: a concurrent request created the same handle between
      // our pre-check and the insert. Repository's `create` re-throws the
      // UNIQUE error after determining the conflict was on `handle`.
      if (err instanceof Error && /UNIQUE/i.test(err.message)) {
        throw new HttpError(409, 'handle_taken', 'that handle is already in use');
      }
      throw err;
    }

    const response: CreateIdentityResponse = {
      id: identity.id,
      handle: identity.handle,
      passcode,
    };
    return c.json(response, 201);
  });
}
