/**
 * Version information for concealment-test
 * Auto-generated by devkit - DO NOT EDIT
 */
export const STORY_VERSION = '1.0.0';
export const BUILD_DATE = '2026-09-12T02:34:54Z';
export const VERSION_INFO = { version: STORY_VERSION, buildDate: BUILD_DATE } as const;
