/**
 * Version information for concealment-test
 * Auto-generated by devkit - DO NOT EDIT
 */
export const STORY_VERSION = '1.0.0';
export const BUILD_DATE = '2026-07-07T07:29:02Z';
export const ENGINE_VERSION = '2.1.1';
export const VERSION_INFO = { version: STORY_VERSION, buildDate: BUILD_DATE, engineVersion: ENGINE_VERSION } as const;
