#!/usr/bin/env bash
#
# setup-zifmia-apache.sh — Apache reverse-proxy + Let's Encrypt for Zifmia (ADR-179).
#
# Idempotent. Run as root: `sudo ./setup-zifmia-apache.sh`.
# Re-running is safe — the script writes only what is missing or stale.
#
# Two-phase strategy:
#   Phase 1: write the port-80 vhost (proxy + ACME carve-out) so
#            certbot's HTTP-01 challenge can reach /.well-known/.
#   Phase 2: certbot certonly --webroot to issue the cert if missing.
#   Phase 3: rewrite the vhost to add the :443 SSL block + HTTP→HTTPS
#            redirect for non-ACME traffic, then reload.
#
# Prerequisites:
#   1. DNS A/AAAA record for zifmia.sharpee.net pointing at this host.
#   2. Zifmia container running and reachable at 127.0.0.1:3000
#      (run deploy-zifmia.sh first).
#   3. Ports 80 and 443 open in the firewall and any upstream NAT.
#
# Env knobs:
#   ZIFMIA_DOMAIN     zifmia.sharpee.net
#   ZIFMIA_BACKEND    127.0.0.1:3000     (where deploy-zifmia.sh bound)
#   CERTBOT_EMAIL     (recommended — used for expiry notifications)

set -euo pipefail

DOMAIN="${ZIFMIA_DOMAIN:-zifmia.sharpee.net}"
BACKEND="${ZIFMIA_BACKEND:-127.0.0.1:3000}"
CERTBOT_EMAIL="${CERTBOT_EMAIL:-}"
SITE_NAME="zifmia"
SITE_AVAIL="/etc/apache2/sites-available/${SITE_NAME}.conf"
WEBROOT="/var/www/html"
CERT_LIVE="/etc/letsencrypt/live/${DOMAIN}/fullchain.pem"
RENEWAL_HOOK="/etc/letsencrypt/renewal-hooks/deploy/reload-apache.sh"

log()  { printf '\033[1;34m[apache]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[apache]\033[0m %s\n' "$*" >&2; }
fail() { printf '\033[1;31m[apache]\033[0m %s\n' "$*" >&2; exit 1; }

# --- Pre-flight ---

if [ "$(id -u)" -ne 0 ]; then
  fail "Run as root: sudo $0"
fi

# DNS is a soft check — warn but don't block. Certbot will fail with a
# clearer error if it can't validate.
if ! getent hosts "${DOMAIN}" >/dev/null 2>&1; then
  warn "DNS lookup for ${DOMAIN} returned no result. Add the A record before Let's Encrypt validation can succeed."
fi

# Backend is a hard check — without it the proxy serves 502s.
if ! curl -fsS "http://${BACKEND}/api/stories" >/dev/null 2>&1; then
  warn "Backend at http://${BACKEND}/api/stories is not responding. Run deploy-zifmia.sh first, or set ZIFMIA_BACKEND= to the right host:port."
fi

# --- Packages ---

log "Ensuring apt packages..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq apache2 certbot python3-certbot-apache curl >/dev/null

# --- Modules ---

log "Enabling Apache modules (proxy proxy_http proxy_wstunnel rewrite ssl headers)..."
a2enmod -q proxy proxy_http proxy_wstunnel rewrite ssl headers >/dev/null

# --- Webroot for ACME challenges ---

install -d -m 0755 "${WEBROOT}/.well-known/acme-challenge"

# --- Generate the vhost content (depends on cert presence) ---

generate_vhost() {
  cat <<EOF
# Zifmia — generated by setup-zifmia-apache.sh (ADR-179).
# DO NOT EDIT BY HAND — re-run the script to regenerate.

<VirtualHost *:80>
    ServerName ${DOMAIN}
    DocumentRoot ${WEBROOT}

    # ACME challenges served from webroot — never proxy these.
    Alias /.well-known/acme-challenge/ ${WEBROOT}/.well-known/acme-challenge/
    <Directory ${WEBROOT}/.well-known/acme-challenge/>
        Options None
        AllowOverride None
        Require all granted
    </Directory>
    ProxyPass /.well-known/ !

EOF

  if [ -f "${CERT_LIVE}" ]; then
    # Cert present → redirect all non-ACME traffic to HTTPS.
    cat <<EOF
    RewriteEngine On
    RewriteCond %{REQUEST_URI} !^/\.well-known/acme-challenge/
    RewriteRule ^/(.*)\$ https://%{HTTP_HOST}/\$1 [R=301,L]

    ErrorLog  \${APACHE_LOG_DIR}/zifmia-error.log
    CustomLog \${APACHE_LOG_DIR}/zifmia-access.log combined
</VirtualHost>

<VirtualHost *:443>
    ServerName ${DOMAIN}

    SSLEngine on
    SSLCertificateFile     /etc/letsencrypt/live/${DOMAIN}/fullchain.pem
    SSLCertificateKeyFile  /etc/letsencrypt/live/${DOMAIN}/privkey.pem
    Include                /etc/letsencrypt/options-ssl-apache.conf

    ProxyPreserveHost On
    ProxyRequests Off

    # WebSocket upgrade — RewriteRule [P] is the only way Apache
    # carries Upgrade: websocket through; ProxyPass alone won't.
    RewriteEngine On
    RewriteCond %{HTTP:Upgrade} =websocket [NC]
    RewriteRule ^/(.*)\$ ws://${BACKEND}/\$1 [P,L]

    # Plain HTTP for everything else.
    ProxyPass         /  http://${BACKEND}/
    ProxyPassReverse  /  http://${BACKEND}/

    RequestHeader set X-Forwarded-Proto "https"

    # Lock heartbeats are 200 ms; 5 min ProxyTimeout is a comfortable
    # upper bound for idle WS sockets.
    ProxyTimeout 300

    ErrorLog  \${APACHE_LOG_DIR}/zifmia-ssl-error.log
    CustomLog \${APACHE_LOG_DIR}/zifmia-ssl-access.log combined
</VirtualHost>
EOF
  else
    # No cert yet → first run: serve over plain HTTP so certbot can
    # validate the domain. The script will rewrite this with the SSL
    # block + redirect after the cert is issued.
    cat <<EOF
    ProxyPreserveHost On
    ProxyRequests Off
    RewriteEngine On
    RewriteCond %{HTTP:Upgrade} =websocket [NC]
    RewriteRule ^/(.*)\$ ws://${BACKEND}/\$1 [P,L]
    ProxyPass         /  http://${BACKEND}/
    ProxyPassReverse  /  http://${BACKEND}/

    ErrorLog  \${APACHE_LOG_DIR}/zifmia-error.log
    CustomLog \${APACHE_LOG_DIR}/zifmia-access.log combined
</VirtualHost>
EOF
  fi
}

# --- Write + reload (idempotent) ---

write_and_reload() {
  local content tmp
  content=$(generate_vhost)
  tmp=$(mktemp)
  echo "${content}" >"${tmp}"
  if [ ! -f "${SITE_AVAIL}" ] || ! diff -q "${tmp}" "${SITE_AVAIL}" >/dev/null 2>&1; then
    log "Writing ${SITE_AVAIL}..."
    mv "${tmp}" "${SITE_AVAIL}"
    chown root:root "${SITE_AVAIL}"
    chmod 0644 "${SITE_AVAIL}"
    if ! a2query -s "${SITE_NAME}" >/dev/null 2>&1; then
      a2ensite -q "${SITE_NAME}" >/dev/null
    fi
    log "Apache configtest..."
    apachectl configtest
    log "Reloading apache2..."
    systemctl reload apache2
  else
    rm -f "${tmp}"
    log "${SITE_AVAIL} already up-to-date."
    if ! a2query -s "${SITE_NAME}" >/dev/null 2>&1; then
      a2ensite -q "${SITE_NAME}" >/dev/null
      systemctl reload apache2
    fi
  fi
}

# Phase 1 — write the current-state vhost (pre-cert if no cert, post-cert if cert exists)
write_and_reload

# Phase 2 — issue cert if missing
if [ ! -f "${CERT_LIVE}" ]; then
  log "Requesting Let's Encrypt cert for ${DOMAIN} (webroot mode)..."
  CERTBOT_ARGS=(certonly --webroot -w "${WEBROOT}" --non-interactive --agree-tos -d "${DOMAIN}")
  if [ -n "${CERTBOT_EMAIL}" ]; then
    CERTBOT_ARGS+=(--email "${CERTBOT_EMAIL}")
  else
    CERTBOT_ARGS+=(--register-unsafely-without-email)
    warn "CERTBOT_EMAIL not set — registering without an email (no expiry reminders). Re-run with CERTBOT_EMAIL=you@example.com to register properly later."
  fi
  certbot "${CERTBOT_ARGS[@]}"
else
  log "Existing cert at ${CERT_LIVE}; skipping issuance. (Auto-renewal runs via the certbot.timer systemd unit.)"
fi

# Phase 3 — rewrite vhost with SSL + redirect now that cert exists
write_and_reload

# --- Renewal deploy hook ---

if [ ! -x "${RENEWAL_HOOK}" ]; then
  log "Installing renewal hook ${RENEWAL_HOOK}..."
  install -d -m 0755 "$(dirname "${RENEWAL_HOOK}")"
  cat >"${RENEWAL_HOOK}" <<'HOOK'
#!/bin/sh
# Installed by setup-zifmia-apache.sh. Reload Apache after a successful
# certificate renewal so the new cert is picked up without a restart.
systemctl reload apache2
HOOK
  chmod 0755 "${RENEWAL_HOOK}"
else
  log "Renewal hook ${RENEWAL_HOOK} already present."
fi

# --- Final smoke check ---

if [ -f "${CERT_LIVE}" ]; then
  log "HTTPS smoke test: curl -fsS https://${DOMAIN}/api/stories"
  if RESP=$(curl -fsS --max-time 10 "https://${DOMAIN}/api/stories" 2>&1); then
    log "Live: ${RESP}"
  else
    warn "HTTPS smoke check failed: ${RESP}"
    warn "Check 'systemctl status apache2' and 'tail -n 50 /var/log/apache2/zifmia-ssl-error.log'."
  fi
else
  warn "Cert was not issued — see certbot output above. The HTTP vhost is live; rerun this script after fixing the underlying issue."
fi

log "Done."
