/**
 * Version information for zifmia client
 * Auto-generated by build.sh - DO NOT EDIT
 */
export const CLIENT_VERSION = '0.1.0-beta';
export const BUILD_DATE = '2026-02-01T04:02:11Z';
export const ENGINE_VERSION = '0.9.61-beta';
export const VERSION_INFO = { version: CLIENT_VERSION, buildDate: BUILD_DATE, engineVersion: ENGINE_VERSION } as const;
