/**
 * build-lexicon.mjs — compile the non-physical noun list into TypeScript source.
 *
 * The lexicon is DATA, but it ships as source: the analyzer runs from a bundle
 * (`dist/cli/sharpee.js`) that no asset-copy step feeds, so a file read at runtime
 * would resolve in the workspace and vanish in the product. A generated module
 * bundles like any other import.
 *
 * THREE BRANCHES ARE DROPPED on the way in, each because it leaks things:
 *
 *   `group`   — a crowd is made of bodies standing somewhere. `crowd`, `audience`,
 *               `company` are exactly what an author implements as scenery.
 *   `measure` — WordNet files `coin` here. So does `rupee`. In a game about a purse
 *               of coins, suppressing `coin` is the worst thing this rule can do.
 *   `communication` — the written-prop class lives here: `deed`, `ticket`, `receipt`,
 *               `playbill`, `warrant`, `charter`, `contract`, `passport`. Every one
 *               is a physical object an interactive fiction hands the player, and
 *               every one would otherwise be suppressed.
 *
 * The cost is real and accepted: `word`, `question`, `talk`, `sentence`, `account`
 * come back into the candidate list, and the short hand list in `incomplete.ts` takes
 * the ones the corpus shows to be pure noise. D6b sets the exchange rate — a missed
 * gap costs more than a junk row.
 *
 * Usage: node scripts/build-lexicon.mjs
 * Owner context: @sharpee/world-index — regeneration only, never run at build time.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const source = join(here, '..', 'data', 'non-physical-nouns.tsv');
const target = join(here, '..', 'src', 'non-physical-nouns.generated.ts');

/** Branches whose members can be physical things in an interactive fiction. */
const DROPPED_BRANCHES = new Set(['group', 'measure', 'communication']);

const rows = readFileSync(source, 'utf8').split('\n');
const words = [];
for (const row of rows) {
  if (row.startsWith('#') || row.trim() === '') continue;
  const [lemma, branches] = row.split('\t');
  if (lemma === 'lemma' || lemma === undefined || branches === undefined) continue;
  const branch = branches.split(';');
  if (branch.some((name) => DROPPED_BRANCHES.has(name))) continue;
  if (!/^[a-z][a-z-]{2,}$/.test(lemma)) continue;
  words.push(lemma);
}
words.sort();

const out = `/**
 * non-physical-nouns.generated.ts — nouns that never name a thing.
 *
 * GENERATED by \`scripts/build-lexicon.mjs\` from \`data/non-physical-nouns.tsv\`.
 * Do not edit: regenerate.
 *
 * Every lemma here has NO sense in Open English WordNet 2024 that inherits from
 * \`physical entity\` — \`saltiness\` cannot be a lump of matter under any amount of
 * pressure. WordNet's \`group\`, \`measure\` and \`communication\`
 * branches are excluded, because \`crowd\`, \`coin\` and \`deed\` are things an
 * interactive fiction implements.
 *
 * Derived from Open English WordNet 2024 (https://github.com/globalwordnet/english-wordnet),
 * licensed CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/). Cite as: John P.
 * McCrae, Alexandre Rademaker, Francis Bond, Ewa Rudnicka and Christiane Fellbaum (2019)
 * "English WordNet 2019 — An Open-Source WordNet for English", GWC 2019, Wroclaw.
 * Changes: filtered to single-word lowercase noun lemmas of three or more letters,
 * removed lemmas with any \`physical entity\` sense, removed the \`group\`,
 * \`measure\` and \`communication\` branches.
 *
 * Public interface: NON_PHYSICAL_NOUNS.
 * Owner context: @sharpee/world-index — the derivation package.
 *
 * @packageDocumentation
 * @see ADR-321 Amendment 2
 */

/** ${words.length} lemmas that refuse a physical reading. */
export const NON_PHYSICAL_NOUNS: ReadonlySet<string> = new Set([
${words.map((word) => `  '${word.replace(/'/g, "\\'")}',`).join('\n')}
]);
`;
writeFileSync(target, out);
console.log(`wrote ${words.length} lemmas to ${target}`);
