/**
 * Version information for browser client
 * Auto-generated by build.sh - DO NOT EDIT
 */
export const CLIENT_VERSION = '1.0.64';
export const BUILD_DATE = '2026-02-02T07:49:26Z';
export const ENGINE_VERSION = '0.9.85';
export const VERSION_INFO = { version: CLIENT_VERSION, buildDate: BUILD_DATE, engineVersion: ENGINE_VERSION } as const;
