/**
 * Version information for browser client
 * Auto-generated by build.sh - DO NOT EDIT
 */
export const CLIENT_VERSION = '1.0.0-beta.20260125.0258';
export const BUILD_DATE = '2026-01-25T02:58:10Z';
export const ENGINE_VERSION = '0.9.60-beta.20260125.0258';
export const VERSION_INFO = { version: CLIENT_VERSION, buildDate: BUILD_DATE, engineVersion: ENGINE_VERSION } as const;
