/**
 * Version information for react client
 * Auto-generated by build.sh - DO NOT EDIT
 */
export const CLIENT_VERSION = '0.1.0-beta.20260124.0738';
export const BUILD_DATE = '2026-01-24T07:38:03Z';
export const ENGINE_VERSION = '0.9.56-beta.20260124.0738';
export const VERSION_INFO = { version: CLIENT_VERSION, buildDate: BUILD_DATE, engineVersion: ENGINE_VERSION } as const;
