/**
 * Version information for react client
 *
 * This file is auto-generated by scripts/update-versions.sh
 * DO NOT EDIT MANUALLY - changes will be overwritten on build.
 */

/** Client version */
export const CLIENT_VERSION = '0.1.0-beta.20260124.0250';

/** Build timestamp (ISO 8601) */
export const BUILD_DATE = '2026-01-24T02:50:34Z';

/** Engine version at build time */
export const ENGINE_VERSION = '0.9.56-beta.20260124.0250';

/** Combined version info object for easy access */
export const VERSION_INFO = {
  version: CLIENT_VERSION,
  buildDate: BUILD_DATE,
  engineVersion: ENGINE_VERSION
} as const;
