/**
 * aliases.ts — `repokit aliases`: the alias-catalog derivation and its freshness gate.
 *
 * The loader's `message-alias-map.ts` is the one curated table of message
 * override aliases: a curator adds one row per new standard-action message
 * id, alias to dotted platform id. The Chord compiler needs only the alias
 * NAMES (it must stay platform-free, so the dotted ids never reach it), and
 * this command derives that names-only set, `packages/chord/src/
 * message-alias-catalog.ts`, from the curated table's keys. Rows are read
 * from the map's SOURCE text, not a built module, so the command needs no
 * dist and the table ships in the same commit as its derivation. `--check`
 * regenerates and diffs against the committed catalog, exit 1 on drift;
 * `repokit verify` runs it beside the grammar and manifest gates.
 *
 * Public interface: AliasesCommand, runAliasesStep, checkAliasCatalogModule,
 * readAliasMap, generateAliasCatalogModule.
 * Owner context: tools/repokit — the in-repo platform build tool (unpublished).
 *
 * References:
 * - ADR-255 D2 — the alias catalog is hand-maintained by a curator; this
 *   command generates nothing from the language pack.
 * - ADR-255 Interface Contract 3 — dotted ids on the loader side only, names
 *   only on the Chord side.
 * - ADR-335 D4 — one curated table; the Chord-side set is derived from it.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { findRepoRoot } from '../repo';
import { Command } from './command';

/** The curated table (read) and the derived catalog (written). */
export const ALIAS_MAP_PATH = 'packages/story-loader/src/message-alias-map.ts';
export const ALIAS_CATALOG_PATH = 'packages/chord/src/message-alias-catalog.ts';

/** One curated row: the kebab alias and the dotted platform message id it names. */
export interface AliasRow {
  alias: string;
  id: string;
}

/**
 * Read the curated rows from the alias map's source text, in file order.
 * A row is one `'<alias>': '<if.action.…>',` line; comments and the
 * surrounding declaration are skipped. Fewer than 500 rows, or an alias
 * that appears twice, is an extraction fault, never a smaller catalog.
 */
export function readAliasMap(root: string): AliasRow[] {
  const src = readFileSync(join(root, ALIAS_MAP_PATH), 'utf8');
  const rows: AliasRow[] = [];
  const seen = new Set<string>();
  for (const m of src.matchAll(/^\s*'([a-z0-9-]+)':\s*'(if\.action\.[a-z0-9_.]+)',?\s*$/gm)) {
    const [, alias, id] = m;
    if (seen.has(alias)) {
      throw new Error(`aliases: ${ALIAS_MAP_PATH} lists \`${alias}\` twice`);
    }
    seen.add(alias);
    rows.push({ alias, id });
  }
  if (rows.length < 500) {
    throw new Error(
      `aliases: ${ALIAS_MAP_PATH} yielded only ${rows.length} rows — extraction broken or file moved`,
    );
  }
  return rows;
}

/** The `if.action.<action>` an alias's platform id belongs to. */
function actionOf(id: string): string {
  const parts = id.split('.');
  return parts.slice(0, 3).join('.');
}

/**
 * Produce the derived catalog's TS text: the curated rows' aliases, in the
 * table's order, one `// if.action.<action>` comment ahead of each run of
 * rows that share an action.
 */
export function generateAliasCatalogModule(root: string): { source: string; aliases: number; actions: number } {
  const rows = readAliasMap(root);
  const actions = new Set(rows.map((r) => actionOf(r.id)));
  const lines: string[] = [];
  lines.push('/**');
  lines.push(' * message-alias-catalog.ts — GENERATED by `repokit aliases` from');
  lines.push(` * ${ALIAS_MAP_PATH}. DO NOT EDIT — add the row to`);
  lines.push(' * the loader\'s curated map and regenerate; the freshness gate');
  lines.push(' * (`repokit aliases --check`, run by `repokit verify`) fails the build on drift.');
  lines.push(' *');
  lines.push(' * The closed set of kebab aliases an author may name in');
  lines.push(' * `override message <alias>`: the keys of the loader\'s curated alias ->');
  lines.push(' * message-id table, names only. The analyzer checks `override message`');
  lines.push(' * against this set and reports an unknown alias with a suggestion. The');
  lines.push(' * dotted platform ids stay on the loader side, so the compiler stays');
  lines.push(' * platform-free; the loader\'s completeness test pins its table to the');
  lines.push(' * live message ids and this set to its keys.');
  lines.push(' *');
  lines.push(' * Public interface: MESSAGE_OVERRIDE_ALIASES.');
  lines.push(' * Owner context: @sharpee/chord (language frontend; browser-safe; generated artifact).');
  lines.push(' *');
  lines.push(` * ${rows.length} aliases across ${actions.size} actions.`);
  lines.push(' *');
  lines.push(' * References:');
  lines.push(' * - ADR-255 D2 — one hand-maintained table; Interface Contract 3 — names');
  lines.push(' *   only on the Chord side.');
  lines.push(' * - ADR-335 D4 — this set is derived from the loader\'s table.');
  lines.push(' */');
  lines.push('');
  lines.push('export const MESSAGE_OVERRIDE_ALIASES: ReadonlySet<string> = new Set([');
  let current: string | null = null;
  for (const row of rows) {
    const action = actionOf(row.id);
    if (action !== current) {
      lines.push(`  // ${action}`);
      current = action;
    }
    lines.push(`  '${row.alias}',`);
  }
  lines.push(']);');
  lines.push('');
  return { source: lines.join('\n'), aliases: rows.length, actions: actions.size };
}

/** Derive and write the catalog. */
export function runAliasesStep(root: string, quiet = false): void {
  const { source, aliases, actions } = generateAliasCatalogModule(root);
  writeFileSync(join(root, ALIAS_CATALOG_PATH), source);
  if (!quiet) console.log(`aliases: ${ALIAS_CATALOG_PATH} regenerated — ${aliases} aliases, ${actions} actions`);
}

/** The freshness gate: the derived text must match the committed catalog byte-for-byte. */
export function checkAliasCatalogModule(root: string): boolean {
  const { source } = generateAliasCatalogModule(root);
  const committed = join(root, ALIAS_CATALOG_PATH);
  if (!existsSync(committed)) return false;
  return source === readFileSync(committed, 'utf8');
}

export class AliasesCommand implements Command {
  readonly name = 'aliases';
  readonly summary = 'Regenerate the chord message-alias catalog from the loader\'s curated map (--check: freshness gate)';

  run(args: string[]): number {
    const root = findRepoRoot();
    if (args.includes('--check')) {
      if (checkAliasCatalogModule(root)) {
        console.log('aliases --check: committed catalog matches the loader\'s alias map');
        return 0;
      }
      console.error(
        `aliases --check: STALE — ${ALIAS_CATALOG_PATH} does not match ` +
          `${ALIAS_MAP_PATH}. Run \`repokit aliases\` and commit the result.`,
      );
      return 1;
    }
    runAliasesStep(root);
    return 0;
  }
}
