/**
 * build.ts — `devkit build`: the full platform+story build pipeline (build.sh
 * update_versions + build_platform + generate_genai_api + build_story + build_bundle).
 * devkit orchestrates; tsf/pnpm compile.
 *
 * Owner context: @sharpee/devkit (ADR-180 Phase 3). Output must match build.sh
 * byte-for-byte (frozen version+date) until build.sh is retired at cutover.
 *
 * Public interface: runBuild(opts). Sub-steps stampVersions/buildPlatform/
 * generateGenaiApi/buildStory are exported for the parity harness + tests.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import {
  PLATFORM_PACKAGES,
  findRepoRoot,
  resolveStory,
  tsfBin,
} from '../repo';
import { runBundle } from './bundle';
import { buildBrowserClient, chordStoryFile } from './browser';
import { buildPlaygroundClient } from './playground';
import { buildZifmiaServer } from './zifmia';

/**
 * The generator name written into stamped version.ts files. build.sh was retired at
 * the ADR-180 Phase 3d cutover (parity verified byte-identical first), so devkit now
 * names itself as the generator.
 */
const GENERATOR = 'devkit';

export interface BuildOptions {
  root?: string;
  /** Story name to build (resolved stories/<name> then tutorials/<name>). */
  story?: string;
  /** Resume the platform build from this package short-name (build.sh --skip). */
  skipTo?: string;
  /** Explicit version to stamp (else read packages/sharpee/package.json). */
  version?: string;
  /** Frozen build date (parity determinism). Defaults to now in build.sh's format. */
  buildDate?: string;
  /** Skip version stamping (build.sh --no-version). */
  noVersion?: boolean;
  /** Skip genai-api generation. */
  noGenai?: boolean;
  /** Run the ESM build pass (needed for browser/story-bundle targets; false for the CLI bundle). */
  esm?: boolean;
  /** Run the bundle step at the end (default true — the full build.sh pipeline). */
  bundle?: boolean;
  /** Also build the browser client (dist/web/<story>/). Implies --esm; requires a story. */
  browser?: boolean;
  /** Also build the story-agnostic playground bundle (ADR-191). Implies --esm; no story. */
  playground?: boolean;
  /** Also build the zifmia multi-user server (tools/zifmia/dist/). Implies --esm. */
  zifmia?: boolean;
  quiet?: boolean;
}

function nowStamp(): string {
  return new Date().toISOString().replace(/\.\d{3}Z$/, 'Z');
}

/** Rewrite a package.json's version, preserving key order + 2-space indent + trailing newline. */
function writePkgVersion(pkgPath: string, version: string): void {
  const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
  pkg.version = version;
  writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
}

/**
 * Stamp versions (build.sh update_versions, CLI/story scope). Returns the resolved
 * SHARPEE_VERSION so callers can log it. See module-level Behavior Statement.
 */
export function stampVersions(root: string, opts: BuildOptions): string {
  const sharpeePkg = join(root, 'packages', 'sharpee', 'package.json');
  const sharpeeVersion = opts.version ?? JSON.parse(readFileSync(sharpeePkg, 'utf8')).version;
  if (opts.noVersion) return sharpeeVersion;

  const buildDate = opts.buildDate ?? nowStamp();

  if (existsSync(sharpeePkg)) writePkgVersion(sharpeePkg, sharpeeVersion);

  // stdlib engine-version.ts — the version action's fallback banner source
  // (platform-issue-sweep Phase 6). Stamped on EVERY build (not just story
  // builds): Chord .story files carry no stamped src/version.ts, so the
  // runtime falls back to this constant; before stamping it was hand-written
  // and permanently stale ('0.9.43-beta.1').
  const engineVersionFile = join(
    root, 'packages', 'stdlib', 'src', 'actions', 'standard', 'version', 'engine-version.ts'
  );
  mkdirSync(dirname(engineVersionFile), { recursive: true });
  writeFileSync(
    engineVersionFile,
    `/**
 * Engine version — the stamped lockstep platform version.
 * Auto-generated by ${GENERATOR} - DO NOT EDIT (stamped by ./repokit build)
 */
export const ENGINE_VERSION = '${sharpeeVersion}';
`,
  );

  // Story version.ts — stories/<name> only (build.sh quirk: tutorials are not stamped).
  // Accepts a path or a name (resolveStory), so `./sharpee build stories/dungeo` stamps too.
  // ADR-252: a Chord `.story` story carries no package.json — its version.ts is stamped
  // from the Story IR by the browser build core, so the pipeline skips it here.
  if (opts.story && !chordStoryFile(root, opts.story)) {
    const resolved = resolveStory(root, opts.story);
    if (resolved && resolved.underStories) {
      const storyVer = JSON.parse(readFileSync(join(resolved.dir, 'package.json'), 'utf8')).version;
      const versionFile = join(resolved.dir, 'src', 'version.ts');
      mkdirSync(dirname(versionFile), { recursive: true });
      writeFileSync(
        versionFile,
        `/**
 * Version information for ${resolved.name}
 * Auto-generated by ${GENERATOR} - DO NOT EDIT
 */
export const STORY_VERSION = '${storyVer}';
export const BUILD_DATE = '${buildDate}';
export const ENGINE_VERSION = '${sharpeeVersion}';
export const VERSION_INFO = { version: STORY_VERSION, buildDate: BUILD_DATE, engineVersion: ENGINE_VERSION } as const;
`,
      );
    }
  }

  // zifmia package.json version (build.sh update_versions stamps it for -c zifmia).
  if (opts.zifmia) {
    const zifmiaPkg = join(root, 'tools', 'zifmia', 'package.json');
    if (existsSync(zifmiaPkg)) writePkgVersion(zifmiaPkg, sharpeeVersion);
  }
  return sharpeeVersion;
}

/** Build all platform packages in dependency order (build.sh build_platform). */
export function buildPlatform(root: string, opts: BuildOptions): void {
  const run = (pkg: string, args: string[]) =>
    execFileSync(pkg, args, { cwd: root, stdio: opts.quiet ? 'ignore' : 'inherit' });

  let skipping = Boolean(opts.skipTo);
  for (const [pkg, dir] of PLATFORM_PACKAGES) {
    if (skipping) {
      if (dir === opts.skipTo) skipping = false;
      else continue;
    }
    run('pnpm', ['--filter', pkg, 'build']);
    // Invariant: assert the compile produced output (precludes the .tsbuildinfo silent no-op class).
    const distIndex = join(root, 'packages', dir, 'dist', 'index.js');
    if (!existsSync(distIndex)) {
      throw new Error(`build of ${pkg} produced no dist/index.js (silent no-op?) at ${distIndex}`);
    }
  }

  if (opts.esm) {
    let esmSkip = Boolean(opts.skipTo);
    for (const [pkg, dir] of PLATFORM_PACKAGES) {
      if (esmSkip) {
        if (dir === opts.skipTo) esmSkip = false;
        else continue;
      }
      if (existsSync(join(root, 'packages', dir, 'tsconfig.esm.json'))) {
        // tsf drives the esm target so esmExtensions post-processing runs (build.sh comment 555-557).
        run(tsfBin(root), ['build', '--condition', 'esm', '--filter', pkg]);
      }
    }
  }
}

/** Generate the genai-api reference (build.sh generate_genai_api). */
export function generateGenaiApi(root: string, opts: BuildOptions): void {
  execFileSync('node', ['scripts/generate-genai-api.js'], {
    cwd: root,
    stdio: opts.quiet ? 'ignore' : 'inherit',
  });
}

/** Build a story package (build.sh build_story + resolve_story_pkg). */
export function buildStory(root: string, story: string, opts: BuildOptions): void {
  const resolved = resolveStory(root, story);
  if (!resolved) throw new Error(`story not found: ${story} (a path, or a stories/|tutorials/ name)`);
  if (!resolved.inRepo) {
    throw new Error(`'${story}' is not an in-repo story (stories/ or tutorials/)`);
  }
  if (!resolved.workspace || !resolved.pkg) {
    // A decoupled standalone story (published @sharpee/* deps, not a workspace
    // member) builds via its own toolchain — the CLI routes these to the
    // standalone build before reaching the platform pipeline.
    throw new Error(
      `'${story}' is a standalone project (not a workspace member) — build it with the standalone 'sharpee build' toolchain`,
    );
  }
  execFileSync('pnpm', ['--filter', resolved.pkg, 'build'], {
    cwd: root,
    stdio: opts.quiet ? 'ignore' : 'inherit',
  });
  if (opts.esm && existsSync(join(resolved.dir, 'tsconfig.esm.json'))) {
    execFileSync(tsfBin(root), ['build', '--condition', 'esm', '--filter', resolved.pkg], {
      cwd: root,
      stdio: opts.quiet ? 'ignore' : 'inherit',
    });
  }
}

/** Run the full build pipeline. */
export function runBuild(opts: BuildOptions = {}): void {
  const root = opts.root ?? findRepoRoot();
  const log = (m: string) => !opts.quiet && console.log(m);

  // Client targets (browser/playground/zifmia) need the ESM build pass (build.sh runs it when a client is requested).
  const effective: BuildOptions =
    opts.browser || opts.playground || opts.zifmia ? { ...opts, esm: true } : opts;
  if (effective.browser && !effective.story) throw new Error('--browser requires a story');

  log('=== devkit build ===');
  const version = stampVersions(root, effective);
  log(`version: ${version}${effective.story ? ` · story: ${effective.story}` : ''}`);
  buildPlatform(root, effective);
  if (!effective.noGenai) generateGenaiApi(root, effective);
  // ADR-252: a Chord `.story` story has no workspace TS package to compile — it ships
  // its source and compiles at boot. buildStory (pnpm --filter) applies to TS stories only.
  const isChordStory = effective.story ? chordStoryFile(root, effective.story) !== null : false;
  if (effective.story && !isChordStory) buildStory(root, effective.story, effective);
  if (effective.bundle !== false) runBundle({ root, quiet: effective.quiet });
  if (effective.browser) buildBrowserClient(root, effective.story!, { quiet: effective.quiet });
  if (effective.playground) buildPlaygroundClient(root, { quiet: effective.quiet });
  if (effective.zifmia) buildZifmiaServer(root, { quiet: effective.quiet });
  log('=== build complete ===');
}

// --- repokit Command wrapper (ADR-187) ---
import { Command } from './command';

/** Parse the platform `build` flags (positional [story] + options). */
function parseBuildArgs(args: string[]): BuildOptions {
  const opts: BuildOptions = {};
  let i = 0;
  while (i < args.length) {
    const a = args[i];
    if (a === '--skip') opts.skipTo = args[++i];
    else if (a === '--version') opts.version = args[++i];
    else if (a === '--build-date') opts.buildDate = args[++i];
    else if (a === '--no-version') opts.noVersion = true;
    else if (a === '--no-genai') opts.noGenai = true;
    else if (a === '--no-bundle') opts.bundle = false;
    else if (a === '--esm') opts.esm = true;
    else if (a === '--browser') opts.browser = true;
    else if (a === '--playground') opts.playground = true;
    else if (a === '--zifmia') opts.zifmia = true;
    else if (a.startsWith('-')) throw new Error(`unknown option: ${a}`);
    else if (!opts.story) opts.story = a;
    else throw new Error(`unexpected argument: ${a}`);
    i++;
  }
  return opts;
}

export class BuildCommand implements Command {
  readonly name = 'build';
  readonly summary = 'Build the platform packages (tsf + pnpm --filter)';
  run(args: string[]): number {
    runBuild(parseBuildArgs(args));
    return 0;
  }
}
