/**
 * manifest.ts — `repokit manifest`: the ADR-276 D2 standing build step.
 *
 * Generates the locale-keyed stdlib manifest module
 * (`packages/chord/src/stdlib-manifest.ts`) — the DATA that lets the Chord
 * analyzer gate stdlib-referencing constructs at compile time while the chord
 * package stays platform-free (it imports nothing; the generator runs out
 * here, outside the runtime graph, exactly like `repokit grammar`). Facts are
 * split per ADR-276 Q-2: locale-neutral (action ids; setting schemas in
 * Phase 5) at top level, locale-owned (grammar shapes, direction words —
 * Phases 4/6) under `locales`, `en-US` the sole entry today.
 *
 * Slices: the stdlib action-id set, read from
 * `packages/stdlib/src/actions/constants.ts` SOURCE (the `readStdlibActionIds`
 * mechanism `repokit grammar` already uses — stdlib builds after chord, so no
 * dist exists to consult); and the per-action standard grammar pattern shapes
 * (locale-owned), derived from the SAME `compileStandardGrammarRules`
 * expansion that emits parser-en-us/src/grammar.ts. `--check` is the
 * freshness gate: regenerate and diff against the committed module, exit 1 on
 * drift; `repokit verify` and the platform build both run it.
 *
 * Public interface: ManifestCommand, runManifestStep, checkManifestModule.
 * Owner context: tools/repokit — the in-repo platform build tool (unpublished).
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { findRepoRoot } from '../repo';
import { Command } from './command';
import { compileStandardGrammarRules, readStdlibActionIds } from './grammar';

const MODULE_PATH = 'packages/chord/src/stdlib-manifest.ts';

/** Produce the generated module's TS text from the stdlib sources of truth. */
export function generateManifestModule(root: string): { source: string; actionIds: number; shapedActions: number } {
  const actionIds = [...readStdlibActionIds(root)].sort();

  // Grammar-shape slice (ADR-276 Phase 4, census 3): the per-action pattern
  // shapes the loader's removeRules compares by EXACT string equality —
  // derived from the same compileStandardGrammarRules expansion that emits
  // parser-en-us/src/grammar.ts, so the manifest and the registered rules
  // cannot drift. The platform-side exception rules (platform-grammar.ts:
  // `?`, `trace …`) are deliberately absent: `?` is unlexable in Chord and
  // `trace` derives no stdlib id, so neither is expressible as a removal —
  // the Chord grammar source IS the removable surface.
  const { rules } = compileStandardGrammarRules(root);
  const grammarShapes = new Map<string, string[]>();
  for (const rule of rules) {
    const list = grammarShapes.get(rule.action) ?? [];
    if (!list.includes(rule.pattern)) list.push(rule.pattern);
    grammarShapes.set(rule.action, list);
  }

  // Setting-schema slice (ADR-276 Phase 5, census 4–6): the Q-3 declarative
  // table, required from story-loader's BUILT dist — the module composes its
  // data (NPC_SHARED reuse), so source-regexing would be fragile where a
  // dist require is exact; the chord-dist precedent above. Locale-NEUTRAL:
  // setting value types are platform facts, not language facts.
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const { SETTING_SCHEMA, HIDING_POSITIONS } = require(join(root, 'packages/story-loader/dist/setting-schema.js')) as {
    SETTING_SCHEMA: ReadonlyMap<string, ReadonlyMap<string, { value: string }>>;
    HIDING_POSITIONS: readonly string[];
  };
  const settingSchema: Array<[string, Array<[string, string]>]> = [];
  for (const [trait, entries] of SETTING_SCHEMA) {
    settingSchema.push([trait, [...entries].map(([key, spec]) => [key, spec.value])]);
  }

  const lines: string[] = [];
  lines.push('/**');
  lines.push(' * stdlib-manifest.ts — GENERATED by `repokit manifest` (ADR-276 D2).');
  lines.push(' * DO NOT EDIT — edit the stdlib source and regenerate; the freshness gate');
  lines.push(' * (`repokit manifest --check`, run by `repokit verify` and the platform');
  lines.push(' * build) fails the build on drift.');
  lines.push(' *');
  lines.push(' * The stdlib facts the analyzer gates against at compile time. Data only —');
  lines.push(' * chord stays platform-FREE (imports nothing) while no longer being');
  lines.push(' * stdlib-IGNORANT (ADR-276 D1). Locale-neutral facts sit at top level;');
  lines.push(' * locale-owned facts (grammar shapes, direction words) go under `locales`,');
  lines.push(' * keyed from day one (Q-2), `en-US` the sole entry.');
  lines.push(' *');
  lines.push(' * Public interface: STDLIB_MANIFEST, StdlibManifest, StdlibLocaleFacts.');
  lines.push(' * Owner context: @sharpee/chord (generated artifact; browser-safe).');
  lines.push(' */');
  lines.push('');
  lines.push('/** Locale-owned stdlib facts (direction words join in a later ADR-276 phase). */');
  lines.push('export interface StdlibLocaleFacts {');
  lines.push('  /**');
  lines.push("   * Standard grammar pattern shapes per action id — the loader's removable");
  lines.push('   * surface (ADR-270 D3), rendered exactly as the registered rule patterns');
  lines.push('   * (`take :item`); removal matching is string equality on these.');
  lines.push('   */');
  lines.push('  grammarShapes: Readonly<Record<string, readonly string[]>>;');
  lines.push('}');
  lines.push('');
  lines.push('export interface StdlibManifest {');
  lines.push('  /** Full stdlib action-id set (`if.action.*`), from stdlib actions/constants.ts. */');
  lines.push('  actionIds: ReadonlySet<string>;');
  lines.push('  /**');
  lines.push('   * Platform trait setting value types (trait adjective → key → type) —');
  lines.push("   * the Q-3 declarative table from story-loader's setting-schema.ts.");
  lines.push("   * Keyless v1 entity refs (`lockable with the iron key`) appear under");
  lines.push("   * their message label (`key`/`tool`). Locale-neutral: platform facts.");
  lines.push('   */');
  lines.push("  settingSchema: Readonly<Record<string, Readonly<Record<string, 'boolean' | 'number' | 'entity-ref' | 'rooms'>>>>;");
  lines.push('  /** The closed hiding-position domain (ratchet G3) — listing order is the message order. */');
  lines.push('  hidingPositions: readonly string[];');
  lines.push('  /** Locale-owned facts, keyed by locale id (ADR-276 Q-2). */');
  lines.push('  locales: Readonly<Record<string, StdlibLocaleFacts>>;');
  lines.push('}');
  lines.push('');
  lines.push('export const STDLIB_MANIFEST: StdlibManifest = {');
  lines.push('  actionIds: new Set([');
  for (const id of actionIds) {
    lines.push(`    ${JSON.stringify(id)},`);
  }
  lines.push('  ]),');
  lines.push('  settingSchema: {');
  for (const [trait, entries] of settingSchema) {
    lines.push(
      `    ${JSON.stringify(trait)}: { ${entries.map(([k, v]) => `${JSON.stringify(k)}: ${JSON.stringify(v)}`).join(', ')} },`,
    );
  }
  lines.push('  },');
  lines.push(`  hidingPositions: [${HIDING_POSITIONS.map((p) => JSON.stringify(p)).join(', ')}],`);
  lines.push('  locales: {');
  lines.push("    'en-US': {");
  lines.push('      grammarShapes: {');
  for (const [action, shapes] of [...grammarShapes.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`        ${JSON.stringify(action)}: [${shapes.map((s) => JSON.stringify(s)).join(', ')}],`);
  }
  lines.push('      },');
  lines.push('    },');
  lines.push('  },');
  lines.push('};');
  lines.push('');
  return { source: lines.join('\n'), actionIds: actionIds.length, shapedActions: grammarShapes.size };
}

/**
 * Generate and write the manifest module (runs before chord compiles in the
 * platform build). The grammar-shape slice needs a chord dist (any prior
 * build's) to compile the grammar source; on a COLD build with no dist yet,
 * the committed module stands in — the verify gate still proves freshness
 * once a dist exists.
 */
export function runManifestStep(root: string, quiet = false): void {
  const needsDist = ['packages/chord/dist/index.js', 'packages/story-loader/dist/setting-schema.js'];
  const missing = needsDist.find((p) => !existsSync(join(root, p)));
  if (missing) {
    if (existsSync(join(root, MODULE_PATH))) {
      if (!quiet) console.log(`manifest: cold build (${missing} not built yet) — using the committed module`);
      return;
    }
    throw new Error(
      `manifest: ${missing} not built and no committed stdlib-manifest.ts — build the platform once, then run \`repokit manifest\``,
    );
  }
  const { source, actionIds, shapedActions } = generateManifestModule(root);
  writeFileSync(join(root, MODULE_PATH), source);
  if (!quiet)
    console.log(`manifest: ${MODULE_PATH} regenerated — ${actionIds} action ids, ${shapedActions} shaped actions`);
}

/** The freshness gate: regenerated text must match the committed module byte-for-byte. */
export function checkManifestModule(root: string): boolean {
  const path = join(root, MODULE_PATH);
  if (!existsSync(path)) return false;
  const { source } = generateManifestModule(root);
  return source === readFileSync(path, 'utf8');
}

export class ManifestCommand implements Command {
  readonly name = 'manifest';
  readonly summary = 'Regenerate the chord stdlib manifest from stdlib source (--check: freshness gate)';

  run(args: string[]): number {
    const root = findRepoRoot();
    if (args.includes('--check')) {
      if (checkManifestModule(root)) {
        console.log('manifest --check: committed module matches the stdlib source');
        return 0;
      }
      console.error(
        'manifest --check: STALE — packages/chord/src/stdlib-manifest.ts does not match ' +
          'the stdlib action surface. Run `repokit manifest` and commit the result.',
      );
      return 1;
    }
    runManifestStep(root);
    return 0;
  }
}
