/**
 * manifest.ts — `repokit manifest`: the ADR-276 D2 standing build step.
 *
 * Generates the locale-keyed stdlib manifest module
 * (`packages/chord/src/stdlib-manifest.ts`) — the DATA that lets the Chord
 * analyzer gate stdlib-referencing constructs at compile time while the chord
 * package stays platform-free (it imports nothing; the generator runs out
 * here, outside the runtime graph, exactly like `repokit grammar`). Facts are
 * split per ADR-276 Q-2: locale-neutral (action ids; setting schemas in
 * Phase 5) at top level, locale-owned (grammar shapes, direction words —
 * Phases 4/6) under `locales`, `en-US` the sole entry today.
 *
 * This phase's slice: the stdlib action-id set, read from
 * `packages/stdlib/src/actions/constants.ts` SOURCE (the `readStdlibActionIds`
 * mechanism `repokit grammar` already uses — stdlib builds after chord, so no
 * dist exists to consult). `--check` is the freshness gate: regenerate and
 * diff against the committed module, exit 1 on drift; `repokit verify` and the
 * platform build (before chord compiles) both run it.
 *
 * Public interface: ManifestCommand, runManifestStep, checkManifestModule.
 * Owner context: tools/repokit — the in-repo platform build tool (unpublished).
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { findRepoRoot } from '../repo';
import { Command } from './command';
import { readStdlibActionIds } from './grammar';

const MODULE_PATH = 'packages/chord/src/stdlib-manifest.ts';

/** Produce the generated module's TS text from the stdlib source of truth. */
export function generateManifestModule(root: string): { source: string; actionIds: number } {
  const actionIds = [...readStdlibActionIds(root)].sort();

  const lines: string[] = [];
  lines.push('/**');
  lines.push(' * stdlib-manifest.ts — GENERATED by `repokit manifest` (ADR-276 D2).');
  lines.push(' * DO NOT EDIT — edit the stdlib source and regenerate; the freshness gate');
  lines.push(' * (`repokit manifest --check`, run by `repokit verify` and the platform');
  lines.push(' * build) fails the build on drift.');
  lines.push(' *');
  lines.push(' * The stdlib facts the analyzer gates against at compile time. Data only —');
  lines.push(' * chord stays platform-FREE (imports nothing) while no longer being');
  lines.push(' * stdlib-IGNORANT (ADR-276 D1). Locale-neutral facts sit at top level;');
  lines.push(' * locale-owned facts (grammar shapes, direction words) go under `locales`,');
  lines.push(' * keyed from day one (Q-2), `en-US` the sole entry.');
  lines.push(' *');
  lines.push(' * Public interface: STDLIB_MANIFEST, StdlibManifest, StdlibLocaleFacts.');
  lines.push(' * Owner context: @sharpee/chord (generated artifact; browser-safe).');
  lines.push(' */');
  lines.push('');
  lines.push('/** Locale-owned stdlib facts — filled by later ADR-276 phases (grammar shapes, direction words). */');
  lines.push('export interface StdlibLocaleFacts {}');
  lines.push('');
  lines.push('export interface StdlibManifest {');
  lines.push('  /** Full stdlib action-id set (`if.action.*`), from stdlib actions/constants.ts. */');
  lines.push('  actionIds: ReadonlySet<string>;');
  lines.push('  /** Locale-owned facts, keyed by locale id (ADR-276 Q-2). */');
  lines.push('  locales: Readonly<Record<string, StdlibLocaleFacts>>;');
  lines.push('}');
  lines.push('');
  lines.push('export const STDLIB_MANIFEST: StdlibManifest = {');
  lines.push('  actionIds: new Set([');
  for (const id of actionIds) {
    lines.push(`    ${JSON.stringify(id)},`);
  }
  lines.push('  ]),');
  lines.push("  locales: { 'en-US': {} },");
  lines.push('};');
  lines.push('');
  return { source: lines.join('\n'), actionIds: actionIds.length };
}

/** Generate and write the manifest module (runs before chord compiles in the platform build). */
export function runManifestStep(root: string, quiet = false): void {
  const { source, actionIds } = generateManifestModule(root);
  writeFileSync(join(root, MODULE_PATH), source);
  if (!quiet) console.log(`manifest: ${MODULE_PATH} regenerated — ${actionIds} action ids`);
}

/** The freshness gate: regenerated text must match the committed module byte-for-byte. */
export function checkManifestModule(root: string): boolean {
  const path = join(root, MODULE_PATH);
  if (!existsSync(path)) return false;
  const { source } = generateManifestModule(root);
  return source === readFileSync(path, 'utf8');
}

export class ManifestCommand implements Command {
  readonly name = 'manifest';
  readonly summary = 'Regenerate the chord stdlib manifest from stdlib source (--check: freshness gate)';

  run(args: string[]): number {
    const root = findRepoRoot();
    if (args.includes('--check')) {
      if (checkManifestModule(root)) {
        console.log('manifest --check: committed module matches the stdlib source');
        return 0;
      }
      console.error(
        'manifest --check: STALE — packages/chord/src/stdlib-manifest.ts does not match ' +
          'the stdlib action surface. Run `repokit manifest` and commit the result.',
      );
      return 1;
    }
    runManifestStep(root);
    return 0;
  }
}
