/**
 * protocol-swift.ts — the Swift emitter for ADR-341 D5's protocol generator.
 *
 * Renders the language-neutral model as one Swift file of `Codable` value
 * types: the shapes the shell decodes off the wire and nothing else. The
 * conveniences the app has always had — schema-version gates, `allEntities`,
 * `hasKind`, the phrase-name view — are NOT emitted; they live in hand-written
 * extensions beside this file, because they are the app's reading of the wire
 * rather than the wire itself. That split is what lets the wire half be
 * regenerated without touching a call site.
 *
 * Public interface: emitSwift.
 * Owner context: tools/repokit — the in-repo platform build tool (unpublished).
 *
 * References:
 * - ADR-341 D5 — Swift is the generator's first target, SharpeeIDE its first consumer.
 */
import { DeclModel, EnumModel, ProtocolModel, StructModel, TypeRef } from './protocol-model';

/** Protocols every emitted value type conforms to. */
const CONFORMANCES = 'Codable, Equatable, Sendable';

/** Swift spelling of a neutral type. */
function swiftType(type: TypeRef): string {
  switch (type.kind) {
    case 'primitive':
      switch (type.name) {
        case 'string':
          return 'String';
        case 'int':
          return 'Int';
        case 'double':
          return 'Double';
        case 'bool':
          return 'Bool';
      }
      break;
    case 'named':
      // Nested names are already qualified from the root down; Swift resolves
      // them from the emitted file's scope.
      return type.name;
    case 'array':
      return `[${swiftType(type.element)}]`;
    case 'map':
      return `[String: ${swiftType(type.value)}]`;
    case 'optional':
      return `${swiftType(type.inner)}?`;
  }
  /* istanbul ignore next — exhaustive above */
  throw new Error(`protocol: no Swift spelling for ${JSON.stringify(type)}`);
}

/** A doc comment as `///` lines at the given indent, or nothing. */
function docLines(doc: string | undefined, indent: string): string[] {
  if (!doc) return [];
  const words = doc.split(/\s+/);
  const lines: string[] = [];
  let current = '';
  for (const word of words) {
    if (current && `${current} ${word}`.length > 88 - indent.length) {
      lines.push(current);
      current = word;
    } else {
      current = current ? `${current} ${word}` : word;
    }
  }
  if (current) lines.push(current);
  return lines.map((line) => `${indent}/// ${line}`);
}

/** Swift case name for a wire string value (`story-language` -> `storyLanguage`). */
function caseName(value: string): string {
  const camel = value.replace(/[-_ ]+(.)/g, (_, c: string) => c.toUpperCase());
  return /^[a-zA-Z_][a-zA-Z0-9_]*$/.test(camel) ? camel : `\`${camel}\``;
}

/** One enum, at the given indent. */
function emitEnum(decl: EnumModel, indent: string): string[] {
  const out = docLines(decl.doc, indent);
  out.push(`${indent}enum ${decl.name}: String, ${CONFORMANCES} {`);
  for (const value of decl.cases) {
    const name = caseName(value);
    out.push(name === value ? `${indent}    case ${name}` : `${indent}    case ${name} = "${value}"`);
  }
  out.push(`${indent}}`);
  return out;
}

/** One struct and everything nested inside it, at the given indent. */
function emitStruct(decl: StructModel, children: DeclModel[], indent: string): string[] {
  const out = docLines(decl.doc, indent);
  out.push(`${indent}struct ${decl.name}: ${CONFORMANCES} {`);
  const inner = `${indent}    `;
  for (const field of decl.fields) {
    out.push(...docLines(field.doc, inner));
    out.push(`${inner}let ${field.name}: ${swiftType(field.type)}`);
  }
  const qualified = decl.nestUnder ? `${decl.nestUnder}.${decl.name}` : decl.name;
  const nested = children.filter((c) => c.nestUnder === qualified).sort((a, b) => a.order - b.order);
  for (const child of nested) {
    out.push('');
    out.push(...emitDecl(child, children, inner));
  }
  out.push(`${indent}}`);
  return out;
}

/** One declaration of either shape. */
function emitDecl(decl: DeclModel, all: DeclModel[], indent: string): string[] {
  return decl.kind === 'enum' ? emitEnum(decl, indent) : emitStruct(decl, all, indent);
}

/**
 * Render the model as one Swift source file.
 *
 * @param model the neutral model, as `buildProtocolModel` produced it
 * @param generatorCommand the command a reader should run to regenerate
 * @returns the complete file text, newline-terminated
 */
export function emitSwift(model: ProtocolModel, generatorCommand: string): string {
  const out: string[] = [];
  out.push('// SharpeeProtocol.swift');
  out.push(`// GENERATED by \`${generatorCommand}\` from the TypeScript wire contract in`);
  out.push('// @sharpee/ide-protocol (ADR-184, ADR-258 D5/D6) and the IDE\'s declared Story IR');
  out.push('// projection. DO NOT EDIT — change the TypeScript and regenerate; the freshness');
  out.push('// gate (`repokit protocol --check`, run by `repokit verify`) fails the build on drift.');
  out.push('//');
  out.push('// These are the wire shapes ONLY. The decode gates and the reading conveniences the');
  out.push('// app has always had live in hand-written extensions beside this file, so the wire');
  out.push('// half regenerates without touching a call site.');
  out.push('//');
  out.push('// Owner context: tools/ide — generated protocol types (ADR-341 D5).');
  out.push('');
  out.push('import Foundation');
  out.push('');

  const top = model.decls.filter((d) => !d.nestUnder).sort((a, b) => a.order - b.order);
  top.forEach((decl, index) => {
    if (index > 0) out.push('');
    out.push(...emitDecl(decl, model.decls, ''));
  });
  out.push('');
  return out.join('\n');
}
