/**
 * Version information for family-zoo-tutorial
 * Auto-generated by devkit - DO NOT EDIT
 */
export const STORY_VERSION = '0.0.1';
export const BUILD_DATE = '2026-09-12T02:35:22Z';
export const VERSION_INFO = { version: STORY_VERSION, buildDate: BUILD_DATE } as const;
