#!/bin/bash
# Build Sharpee platform + Dungeo story for testing (Ubuntu version)
# Uses 'npx pnpm' instead of 'pnpm' for environments without global pnpm
#
# Usage:
#   bash scripts/build-dungeo-ubuntu.sh                  # Build everything
#   bash scripts/build-dungeo-ubuntu.sh --skip stdlib    # Skip to stdlib in platform build
#   bash scripts/build-dungeo-ubuntu.sh --skip dungeo    # Only rebuild dungeo (platform already built)
#
# Output: dist/sharpee.js ready for transcript testing

set -e

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

# Parse arguments
SKIP_TO=""
if [ "$1" = "--skip" ] && [ -n "$2" ]; then
    SKIP_TO="$2"
fi

# Increment patch version for Dungeo (patch only, prerelease tags untouched)
# If patch reaches 999, roll to next minor
increment_version() {
    local DUNGEO_PKG="stories/dungeo/package.json"
    local VERSION_FILE="stories/dungeo/src/version.ts"
    local ENGINE_PKG="packages/sharpee/package.json"

    if [ ! -f "$DUNGEO_PKG" ]; then
        return
    fi

    # Read current version from package.json
    CURRENT_VERSION=$(node -p "require('./$DUNGEO_PKG').version")

    # Extract base version and prerelease separately
    BASE_VERSION=$(echo "$CURRENT_VERSION" | sed 's/-.*//')
    PRERELEASE=$(echo "$CURRENT_VERSION" | grep -oP '(?<=-).*' || echo "")

    # Parse base version parts
    MAJOR=$(echo "$BASE_VERSION" | cut -d. -f1)
    MINOR=$(echo "$BASE_VERSION" | cut -d. -f2)
    PATCH=$(echo "$BASE_VERSION" | cut -d. -f3)

    # Increment patch, roll minor if needed
    if [ "$PATCH" -ge 999 ]; then
        MINOR=$((MINOR + 1))
        PATCH=0
    else
        PATCH=$((PATCH + 1))
    fi

    # Reconstruct version (preserve prerelease if present)
    if [ -n "$PRERELEASE" ]; then
        NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}-${PRERELEASE}"
    else
        NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
    fi

    # Update package.json with new version
    node -e "
      const fs = require('fs');
      const pkg = require('./$DUNGEO_PKG');
      pkg.version = '$NEW_VERSION';
      fs.writeFileSync('$DUNGEO_PKG', JSON.stringify(pkg, null, 2) + '\n');
    "

    # Get engine version
    ENGINE_VERSION=$(node -p "require('./$ENGINE_PKG').version")

    # Generate build timestamp
    BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

    # Generate version.ts
    cat > "$VERSION_FILE" << EOF
/**
 * Version information for Dungeo
 *
 * This file is auto-generated by the build script.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 */

/** Story version (auto-incremented on build) */
export const STORY_VERSION = '$NEW_VERSION';

/** Build timestamp (ISO 8601) */
export const BUILD_DATE = '$BUILD_DATE';

/** Engine version at build time */
export const ENGINE_VERSION = '$ENGINE_VERSION';

/** Combined version info object for easy access */
export const VERSION_INFO = {
  version: STORY_VERSION,
  buildDate: BUILD_DATE,
  engineVersion: ENGINE_VERSION
} as const;
EOF

    echo "[dungeo version] $CURRENT_VERSION → $NEW_VERSION (built $BUILD_DATE)"
}

# If skipping to dungeo, just build dungeo
if [ "$SKIP_TO" = "dungeo" ]; then
    echo "=== Building Dungeo Only ==="
    increment_version

    echo -n "[dungeo] "
    if npx pnpm --filter "@sharpee/story-dungeo" build > /dev/null 2>&1; then
        echo "✓"
    else
        echo "✗ FAILED"
        npx pnpm --filter "@sharpee/story-dungeo" build 2>&1 | tail -20
        exit 1
    fi

    echo ""
    echo "=== Dungeo Build Complete ==="
    echo "Test with: node dist/sharpee.js --play"
    exit 0
fi

# Build platform first
if [ -n "$SKIP_TO" ]; then
    bash "$REPO_ROOT/scripts/build-platform-ubuntu.sh" --skip "$SKIP_TO"
else
    bash "$REPO_ROOT/scripts/build-platform-ubuntu.sh"
fi

echo ""
increment_version

# Build dungeo story
echo "=== Building Dungeo Story ==="
echo -n "[dungeo] "
if npx pnpm --filter "@sharpee/story-dungeo" build > /dev/null 2>&1; then
    echo "✓"
else
    echo "✗ FAILED"
    npx pnpm --filter "@sharpee/story-dungeo" build 2>&1 | tail -20
    exit 1
fi

echo ""
echo "=== Dungeo Build Complete ==="
echo "Test with: node dist/sharpee.js --play"
echo "Or: node dist/sharpee.js --test stories/dungeo/tests/transcripts/<name>.transcript"
