#!/bin/bash
# Build Sharpee platform + Dungeo story for testing
#
# Usage:
#   ./scripts/build-dungeo.sh                  # Build everything
#   ./scripts/build-dungeo.sh --skip stdlib    # Skip to stdlib in platform build
#   ./scripts/build-dungeo.sh --skip dungeo    # Only rebuild dungeo (platform already built)
#
# Output: dist/sharpee.js ready for transcript testing

set -e

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

# Parse arguments
SKIP_TO=""
if [ "$1" = "--skip" ] && [ -n "$2" ]; then
    SKIP_TO="$2"
fi

# Update versions with date-based prerelease tag (beta.YYYYMMDD.HHMM)
# Base version (major.minor.patch) is preserved; only the date portion updates
update_versions() {
    local SHARPEE_PKG="packages/sharpee/package.json"
    local DUNGEO_PKG="stories/dungeo/package.json"
    local DUNGEO_VERSION_FILE="stories/dungeo/src/version.ts"
    local BROWSER_PKG="packages/platforms/browser-en-us/package.json"
    local BROWSER_VERSION_FILE="packages/platforms/browser-en-us/src/version.ts"

    # Generate date-based prerelease tag: beta.YYYYMMDD.HHMM
    local DATE_TAG=$(date -u +"%Y%m%d.%H%M")
    local BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

    # Update Sharpee version
    if [ -f "$SHARPEE_PKG" ]; then
        local SHARPEE_CURRENT=$(node -p "require('./$SHARPEE_PKG').version")
        local SHARPEE_BASE=$(echo "$SHARPEE_CURRENT" | sed 's/-.*//')
        local SHARPEE_NEW="${SHARPEE_BASE}-beta.${DATE_TAG}"

        node -e "
          const fs = require('fs');
          const pkg = require('./$SHARPEE_PKG');
          pkg.version = '$SHARPEE_NEW';
          fs.writeFileSync('$SHARPEE_PKG', JSON.stringify(pkg, null, 2) + '\n');
        "
        echo "[sharpee version] $SHARPEE_CURRENT → $SHARPEE_NEW"
    fi

    # Update Dungeo version
    if [ -f "$DUNGEO_PKG" ]; then
        local DUNGEO_CURRENT=$(node -p "require('./$DUNGEO_PKG').version")
        local DUNGEO_BASE=$(echo "$DUNGEO_CURRENT" | sed 's/-.*//')
        local DUNGEO_NEW="${DUNGEO_BASE}-beta.${DATE_TAG}"

        node -e "
          const fs = require('fs');
          const pkg = require('./$DUNGEO_PKG');
          pkg.version = '$DUNGEO_NEW';
          fs.writeFileSync('$DUNGEO_PKG', JSON.stringify(pkg, null, 2) + '\n');
        "

        # Get engine version (just updated above)
        local ENGINE_VERSION="${SHARPEE_NEW}"

        # Generate dungeo version.ts
        cat > "$DUNGEO_VERSION_FILE" << EOF
/**
 * Version information for Dungeo
 *
 * This file is auto-generated by the build script.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 */

/** Story version */
export const STORY_VERSION = '$DUNGEO_NEW';

/** Build timestamp (ISO 8601) */
export const BUILD_DATE = '$BUILD_DATE';

/** Engine version at build time */
export const ENGINE_VERSION = '$ENGINE_VERSION';

/** Combined version info object for easy access */
export const VERSION_INFO = {
  version: STORY_VERSION,
  buildDate: BUILD_DATE,
  engineVersion: ENGINE_VERSION
} as const;
EOF
        echo "[dungeo version] $DUNGEO_CURRENT → $DUNGEO_NEW"
    fi

    # Update Browser client version
    if [ -f "$BROWSER_PKG" ]; then
        local BROWSER_CURRENT=$(node -p "require('./$BROWSER_PKG').version")
        local BROWSER_BASE=$(echo "$BROWSER_CURRENT" | sed 's/-.*//')
        local BROWSER_NEW="${BROWSER_BASE}-beta.${DATE_TAG}"

        node -e "
          const fs = require('fs');
          const pkg = require('./$BROWSER_PKG');
          pkg.version = '$BROWSER_NEW';
          fs.writeFileSync('$BROWSER_PKG', JSON.stringify(pkg, null, 2) + '\n');
        "

        # Create version.ts directory if needed
        mkdir -p "$(dirname "$BROWSER_VERSION_FILE")"

        # Generate browser version.ts
        cat > "$BROWSER_VERSION_FILE" << EOF
/**
 * Version information for Browser Client
 *
 * This file is auto-generated by the build script.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 */

/** Client version */
export const CLIENT_VERSION = '$BROWSER_NEW';

/** Build timestamp (ISO 8601) */
export const BUILD_DATE = '$BUILD_DATE';

/** Engine version at build time */
export const ENGINE_VERSION = '${SHARPEE_NEW}';

/** Combined version info object for easy access */
export const VERSION_INFO = {
  version: CLIENT_VERSION,
  buildDate: BUILD_DATE,
  engineVersion: ENGINE_VERSION
} as const;
EOF
        echo "[browser version] $BROWSER_CURRENT → $BROWSER_NEW"
    fi
}

# If skipping to dungeo, just build dungeo
if [ "$SKIP_TO" = "dungeo" ]; then
    echo "=== Building Dungeo Only ==="
    update_versions

    echo -n "[dungeo] "
    if pnpm --filter "@sharpee/story-dungeo" build > /dev/null 2>&1; then
        echo "✓"
    else
        echo "✗ FAILED"
        pnpm --filter "@sharpee/story-dungeo" build 2>&1 | tail -20
        exit 1
    fi

    echo ""
    echo "=== Dungeo Build Complete ==="
    echo "Test with: node dist/sharpee.js --play"
    exit 0
fi

# Build platform first
if [ -n "$SKIP_TO" ]; then
    "$REPO_ROOT/scripts/build-platform.sh" --skip "$SKIP_TO"
else
    "$REPO_ROOT/scripts/build-platform.sh"
fi

echo ""
update_versions

# Build dungeo story
echo "=== Building Dungeo Story ==="
echo -n "[dungeo] "
if pnpm --filter "@sharpee/story-dungeo" build > /dev/null 2>&1; then
    echo "✓"
else
    echo "✗ FAILED"
    pnpm --filter "@sharpee/story-dungeo" build 2>&1 | tail -20
    exit 1
fi

echo ""
echo "=== Dungeo Build Complete ==="
echo "Test with: node dist/sharpee.js --play"
echo "Or: ./scripts/fast-transcript-test.sh stories/dungeo --all"
