#!/bin/bash
# Bundle all Sharpee packages into a single distributable
# Usage: ./scripts/bundle-sharpee.sh

set -e

echo "=== Bundling Sharpee ==="

# ========================================
# Auto-increment version for Dungeo
# ========================================
DUNGEO_PKG="stories/dungeo/package.json"
VERSION_FILE="stories/dungeo/src/version.ts"
ENGINE_PKG="packages/engine/package.json"

if [ -f "$DUNGEO_PKG" ]; then
  echo "Incrementing Dungeo version..."

  # Read current version from package.json
  CURRENT_VERSION=$(node -p "require('./$DUNGEO_PKG').version")

  # Parse version parts (e.g., 1.0.0-alpha.1 -> 1.0.0, alpha.1)
  BASE_VERSION=$(echo "$CURRENT_VERSION" | sed 's/-.*//')
  PRERELEASE=$(echo "$CURRENT_VERSION" | grep -oP '(?<=-).+' || echo "")

  if [ -n "$PRERELEASE" ]; then
    # Has prerelease tag (e.g., alpha.1)
    PRERELEASE_TAG=$(echo "$PRERELEASE" | sed 's/\.[0-9]*$//')
    PRERELEASE_NUM=$(echo "$PRERELEASE" | grep -oP '\d+$' || echo "0")
    NEW_PRERELEASE_NUM=$((PRERELEASE_NUM + 1))
    NEW_VERSION="${BASE_VERSION}-${PRERELEASE_TAG}.${NEW_PRERELEASE_NUM}"
  else
    # No prerelease, increment patch
    MAJOR=$(echo "$BASE_VERSION" | cut -d. -f1)
    MINOR=$(echo "$BASE_VERSION" | cut -d. -f2)
    PATCH=$(echo "$BASE_VERSION" | cut -d. -f3)
    NEW_PATCH=$((PATCH + 1))
    NEW_VERSION="${MAJOR}.${MINOR}.${NEW_PATCH}"
  fi

  # Update package.json with new version
  node -e "
    const fs = require('fs');
    const pkg = require('./$DUNGEO_PKG');
    pkg.version = '$NEW_VERSION';
    fs.writeFileSync('$DUNGEO_PKG', JSON.stringify(pkg, null, 2) + '\n');
  "

  # Get engine version
  ENGINE_VERSION=$(node -p "require('./$ENGINE_PKG').version")

  # Generate build timestamp
  BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

  # Generate version.ts
  cat > "$VERSION_FILE" << EOF
/**
 * Version information for Dungeo
 *
 * This file is auto-generated by the bundle script.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 */

/** Story version (auto-incremented on bundle) */
export const STORY_VERSION = '$NEW_VERSION';

/** Build timestamp (ISO 8601) */
export const BUILD_DATE = '$BUILD_DATE';

/** Engine version at build time */
export const ENGINE_VERSION = '$ENGINE_VERSION';

/** Combined version info object for easy access */
export const VERSION_INFO = {
  version: STORY_VERSION,
  buildDate: BUILD_DATE,
  engineVersion: ENGINE_VERSION
} as const;
EOF

  echo "  Previous: $CURRENT_VERSION"
  echo "  New:      $NEW_VERSION"
  echo "  Built:    $BUILD_DATE"
  echo ""
fi

# Ensure packages are built first (only @sharpee/* packages, not stories)
echo "Building Sharpee packages..."
pnpm --filter '@sharpee/*' \
  --filter '!@sharpee/story-*' \
  --filter '!@sharpee/platform-*' \
  build

# Create dist directory
mkdir -p dist

# Use esbuild to bundle everything
echo "Bundling with esbuild..."
npx esbuild \
  scripts/bundle-entry.js \
  --bundle \
  --platform=node \
  --target=node18 \
  --outfile=dist/sharpee.js \
  --external:readline \
  --format=cjs \
  --sourcemap

# Generate TypeScript declarations (combine from packages)
echo "Generating type declarations..."
cat > dist/sharpee.d.ts << 'EOF'
// Auto-generated Sharpee type declarations
// This is a combined re-export of all package types

export * from '../packages/core/dist/index';
export * from '../packages/if-domain/dist/index';
export * from '../packages/world-model/dist/index';
export * from '../packages/stdlib/dist/index';
export * from '../packages/engine/dist/index';
export * from '../packages/parser-en-us/dist/index';
export * from '../packages/lang-en-us/dist/index';
export * from '../packages/event-processor/dist/index';
export * from '../packages/text-blocks/dist/index';
export * from '../packages/text-service/dist/index';
EOF

# Measure bundle size
BUNDLE_SIZE=$(ls -lh dist/sharpee.js | awk '{print $5}')
echo ""
echo "=== Bundle Complete ==="
echo "Output: dist/sharpee.js ($BUNDLE_SIZE)"
echo ""

# Test load time
echo "Testing load time..."
node -e "
const start = Date.now();
require('./dist/sharpee.js');
console.log('Bundle loaded in ' + (Date.now() - start) + 'ms');
"
