#!/bin/bash
# Update version files with date-based prerelease tags
#
# Usage:
#   ./scripts/update-versions.sh                        # Update sharpee only
#   ./scripts/update-versions.sh --story dungeo         # Update sharpee + story
#   ./scripts/update-versions.sh --story dungeo --client browser  # Update all
#
# Generates version.ts files with format: X.Y.Z-beta.YYYYMMDD.HHMM

set -e

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

# Parse arguments
STORY=""
CLIENT=""

while [[ $# -gt 0 ]]; do
    case $1 in
        -s|--story)
            STORY="$2"
            shift 2
            ;;
        -c|--client)
            CLIENT="$2"
            shift 2
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Generate date-based prerelease tag: beta.YYYYMMDD.HHMM
DATE_TAG=$(date -u +"%Y%m%d.%H%M")
BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

echo "=== Updating Versions (${DATE_TAG}) ==="

# Update Sharpee version (always)
update_sharpee_version() {
    local SHARPEE_PKG="packages/sharpee/package.json"

    if [ ! -f "$SHARPEE_PKG" ]; then
        echo "[sharpee] package.json not found"
        return 1
    fi

    local CURRENT=$(node -p "require('./$SHARPEE_PKG').version")
    local BASE=$(echo "$CURRENT" | sed 's/-.*//')
    local NEW="${BASE}-beta.${DATE_TAG}"

    node -e "
      const fs = require('fs');
      const pkg = require('./$SHARPEE_PKG');
      pkg.version = '$NEW';
      fs.writeFileSync('$SHARPEE_PKG', JSON.stringify(pkg, null, 2) + '\n');
    "
    echo "[sharpee] $CURRENT -> $NEW"

    # Export for other functions
    SHARPEE_VERSION="$NEW"
}

# Update story version and generate version.ts
update_story_version() {
    local STORY_NAME="$1"
    local STORY_PKG="stories/${STORY_NAME}/package.json"
    local VERSION_FILE="stories/${STORY_NAME}/src/version.ts"

    if [ ! -f "$STORY_PKG" ]; then
        echo "[${STORY_NAME}] package.json not found"
        return 1
    fi

    local CURRENT=$(node -p "require('./$STORY_PKG').version")
    local BASE=$(echo "$CURRENT" | sed 's/-.*//')
    local NEW="${BASE}-beta.${DATE_TAG}"

    # Update package.json
    node -e "
      const fs = require('fs');
      const pkg = require('./$STORY_PKG');
      pkg.version = '$NEW';
      fs.writeFileSync('$STORY_PKG', JSON.stringify(pkg, null, 2) + '\n');
    "

    # Generate version.ts
    mkdir -p "$(dirname "$VERSION_FILE")"
    cat > "$VERSION_FILE" << EOF
/**
 * Version information for ${STORY_NAME}
 *
 * This file is auto-generated by scripts/update-versions.sh
 * DO NOT EDIT MANUALLY - changes will be overwritten on build.
 */

/** Story version */
export const STORY_VERSION = '${NEW}';

/** Build timestamp (ISO 8601) */
export const BUILD_DATE = '${BUILD_DATE}';

/** Engine version at build time */
export const ENGINE_VERSION = '${SHARPEE_VERSION}';

/** Combined version info object for easy access */
export const VERSION_INFO = {
  version: STORY_VERSION,
  buildDate: BUILD_DATE,
  engineVersion: ENGINE_VERSION
} as const;
EOF

    echo "[${STORY_NAME}] $CURRENT -> $NEW"
}

# Update client version and generate version.ts
update_client_version() {
    local CLIENT_TYPE="$1"
    local CLIENT_PKG="packages/platforms/${CLIENT_TYPE}-en-us/package.json"
    local VERSION_FILE="packages/platforms/${CLIENT_TYPE}-en-us/src/version.ts"

    if [ ! -f "$CLIENT_PKG" ]; then
        echo "[${CLIENT_TYPE}] package.json not found"
        return 1
    fi

    local CURRENT=$(node -p "require('./$CLIENT_PKG').version")
    local BASE=$(echo "$CURRENT" | sed 's/-.*//')
    local NEW="${BASE}-beta.${DATE_TAG}"

    # Update package.json
    node -e "
      const fs = require('fs');
      const pkg = require('./$CLIENT_PKG');
      pkg.version = '$NEW';
      fs.writeFileSync('$CLIENT_PKG', JSON.stringify(pkg, null, 2) + '\n');
    "

    # Generate version.ts
    mkdir -p "$(dirname "$VERSION_FILE")"
    cat > "$VERSION_FILE" << EOF
/**
 * Version information for ${CLIENT_TYPE} client
 *
 * This file is auto-generated by scripts/update-versions.sh
 * DO NOT EDIT MANUALLY - changes will be overwritten on build.
 */

/** Client version */
export const CLIENT_VERSION = '${NEW}';

/** Build timestamp (ISO 8601) */
export const BUILD_DATE = '${BUILD_DATE}';

/** Engine version at build time */
export const ENGINE_VERSION = '${SHARPEE_VERSION}';

/** Combined version info object for easy access */
export const VERSION_INFO = {
  version: CLIENT_VERSION,
  buildDate: BUILD_DATE,
  engineVersion: ENGINE_VERSION
} as const;
EOF

    echo "[${CLIENT_TYPE}] $CURRENT -> $NEW"
}

# Always update sharpee
update_sharpee_version

# Update story if specified
if [ -n "$STORY" ]; then
    update_story_version "$STORY"
fi

# Update client if specified
if [ -n "$CLIENT" ]; then
    update_client_version "$CLIENT"
fi

echo ""
