/**
 * Version information for armoured
 * Auto-generated by devkit - DO NOT EDIT
 */
export const STORY_VERSION = '0.9.79-beta';
export const BUILD_DATE = '2026-09-10T15:41:47Z';
export const ENGINE_VERSION = '5.3.1';
export const VERSION_INFO = { version: STORY_VERSION, buildDate: BUILD_DATE, engineVersion: ENGINE_VERSION } as const;
