#!/usr/bin/env bash
#
# Build a Zifmia release (frontend runner + Tauri DMG installer).
#
# Full pipeline using tsf for TypeScript compilation:
#   1. Update version files
#   2. tsf build --target local,esm (TypeScript compilation)
#   3. Bundle runner frontend (esbuild via tsf loader)
#   4. cargo tauri build - DMG installer
#
# Usage:
#   ./build-release.sh [options]
#
# Options:
#   --theme <name>       Zifmia theme (classic-light|modern-dark|retro-terminal|paper)
#   --version <ver>      Explicit version string (e.g. 0.9.91)
#   --skip-platform      Skip steps 1-2 (versions + TypeScript compilation)
#   --skip-frontend      Skip steps 1-3 entirely, go straight to cargo tauri build
#   --debug              Build a debug (unoptimised) Tauri binary
#
# Examples:
#   ./build-release.sh
#   ./build-release.sh --theme modern-dark
#   ./build-release.sh --skip-platform
#   ./build-release.sh --skip-frontend

set -euo pipefail

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SRC_TAURI="$SCRIPT_DIR/src-tauri"
RUNNER_DIST="$REPO_ROOT/dist/runner"
TSF_CLI="$REPO_ROOT/../tsf/dist/cli/index.js"
BUNDLE_SCRIPT="$SCRIPT_DIR/scripts/bundle-runner.cjs"

# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------
THEME="classic-light"
VERSION=""
SKIP_PLATFORM=false
SKIP_FRONTEND=false
DEBUG=false

# ---------------------------------------------------------------------------
# Parse args
# ---------------------------------------------------------------------------
while [[ $# -gt 0 ]]; do
    case "$1" in
        --theme)       THEME="$2"; shift 2 ;;
        --version)     VERSION="$2"; shift 2 ;;
        --skip-platform) SKIP_PLATFORM=true; shift ;;
        --skip-frontend) SKIP_FRONTEND=true; shift ;;
        --debug)       DEBUG=true; shift ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

# Validate theme
case "$THEME" in
    classic-light|modern-dark|retro-terminal|paper) ;;
    *) echo "Invalid theme: $THEME"; exit 1 ;;
esac

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
step()  { printf '\n\033[0;36m=== %s ===\033[0m\n' "$1"; }
ok()    { printf '  \033[0;32m[OK]\033[0m %s\n' "$1"; }
fail()  { printf '  \033[0;31m[FAIL]\033[0m %s\n' "$1"; exit 1; }

# ---------------------------------------------------------------------------
# Prerequisites
# ---------------------------------------------------------------------------
command -v node  >/dev/null 2>&1 || fail "node is not installed or not on PATH"
command -v cargo >/dev/null 2>&1 || fail "cargo is not installed or not on PATH"

if [ ! -f "$TSF_CLI" ]; then
    echo "tsf CLI not found at $TSF_CLI"
    echo "Build tsf first: cd ../tsf && npm run build"
    exit 1
fi

TAURI_VER=$(cargo tauri --version 2>/dev/null) || fail "cargo-tauri CLI not found. Install with: cargo install tauri-cli"
printf '\033[0;90mTauri CLI: %s\033[0m\n' "$TAURI_VER"
printf '\033[0;90mtsf CLI:   %s\033[0m\n' "$TSF_CLI"

# ===================================================================
# Step 1 - Version updates
# ===================================================================
if [ "$SKIP_FRONTEND" = false ] && [ "$SKIP_PLATFORM" = false ]; then
    step "Step 1: Update Versions"

    BUILD_DATE=$(date -u '+%Y-%m-%dT%H:%M:%SZ')

    if [ -n "$VERSION" ]; then
        SHARPEE_VERSION="$VERSION"
    else
        BASE=$(node -e "const p=require('$REPO_ROOT/packages/sharpee/package.json'); console.log(p.version.replace(/-.*/, ''))")
        SHARPEE_VERSION="${BASE}-beta"
    fi

    NATIVE_VERSION="${SHARPEE_VERSION%%-*}"

    # packages/sharpee/package.json
    node -e "
      const fs = require('fs');
      const p = '$REPO_ROOT/packages/sharpee/package.json';
      const j = JSON.parse(fs.readFileSync(p, 'utf8'));
      j.version = '$SHARPEE_VERSION';
      fs.writeFileSync(p, JSON.stringify(j, null, 2) + '\n');
    "
    ok "sharpee $SHARPEE_VERSION"

    # packages/zifmia/package.json
    node -e "
      const fs = require('fs');
      const p = '$REPO_ROOT/packages/zifmia/package.json';
      const j = JSON.parse(fs.readFileSync(p, 'utf8'));
      j.version = '$SHARPEE_VERSION';
      fs.writeFileSync(p, JSON.stringify(j, null, 2) + '\n');
    "

    # packages/zifmia/src/version.ts
    cat > "$REPO_ROOT/packages/zifmia/src/version.ts" <<VEOF
/**
 * Version information for zifmia client
 * Auto-generated by build-release.sh - DO NOT EDIT
 */
export const CLIENT_VERSION = '$SHARPEE_VERSION';
export const BUILD_DATE = '$BUILD_DATE';
export const ENGINE_VERSION = '$SHARPEE_VERSION';
export const VERSION_INFO = { version: CLIENT_VERSION, buildDate: BUILD_DATE, engineVersion: ENGINE_VERSION } as const;
VEOF

    # src-tauri/tauri.conf.json
    node -e "
      const fs = require('fs');
      const p = '$SRC_TAURI/tauri.conf.json';
      const j = JSON.parse(fs.readFileSync(p, 'utf8'));
      j.version = '$NATIVE_VERSION';
      fs.writeFileSync(p, JSON.stringify(j, null, 2) + '\n');
    "

    # src-tauri/Cargo.toml
    sed -i '' "s/^version = \".*\"/version = \"$NATIVE_VERSION\"/" "$SRC_TAURI/Cargo.toml"

    ok "zifmia $SHARPEE_VERSION (native: $NATIVE_VERSION)"
else
    printf '\n\033[0;33m=== Step 1: Skipped ===\033[0m\n'
fi

# ===================================================================
# Step 2 - TypeScript compilation via tsf
# ===================================================================
if [ "$SKIP_FRONTEND" = false ] && [ "$SKIP_PLATFORM" = false ]; then
    step "Step 2: TypeScript Compilation (tsf)"

    pushd "$REPO_ROOT" > /dev/null
    node "$TSF_CLI" build --target local,esm --verbose || fail "tsf build failed"
    popd > /dev/null
else
    printf '\n\033[0;33m=== Step 2: Skipped ===\033[0m\n'
fi

# ===================================================================
# Step 3 - Bundle runner frontend
# ===================================================================
if [ "$SKIP_FRONTEND" = false ]; then
    step "Step 3: Bundle Runner Frontend"

    node "$BUNDLE_SCRIPT" --theme "$THEME" || fail "Runner bundling failed"
else
    printf '\n\033[0;33m=== Step 3: Skipped (--skip-frontend) ===\033[0m\n'
fi

# Verify dist/runner exists before Tauri build
if [ ! -f "$RUNNER_DIST/index.html" ]; then
    fail "Runner frontend not found at $RUNNER_DIST. Run without --skip-frontend first."
fi

# ===================================================================
# Step 4 - Tauri build
# ===================================================================
step "Step 4: Cargo Tauri Build"

TAURI_ARGS=(tauri build --bundles dmg)
if [ "$DEBUG" = true ]; then
    TAURI_ARGS+=(--debug)
fi

printf '  \033[0;90mcargo %s\033[0m\n' "${TAURI_ARGS[*]}"
pushd "$SRC_TAURI" > /dev/null
cargo "${TAURI_ARGS[@]}" || fail "Tauri build failed"
popd > /dev/null

# ===================================================================
# Summary
# ===================================================================
echo ""
printf '\033[0;32m=== Build Complete ===\033[0m\n'

PROFILE="release"
if [ "$DEBUG" = true ]; then PROFILE="debug"; fi
BUNDLE_DIR="$SRC_TAURI/target/$PROFILE/bundle"

DMG=$(find "$BUNDLE_DIR/dmg" -name '*.dmg' 2>/dev/null | head -1)
if [ -n "$DMG" ]; then
    SIZE_MB=$(du -m "$DMG" | cut -f1)
    printf '  DMG: %s (%s MB)\n' "$DMG" "$SIZE_MB"

    # Copy to macos-builds for easy access
    BUILDS_DIR="$REPO_ROOT/macos-builds"
    mkdir -p "$BUILDS_DIR"
    cp "$DMG" "$BUILDS_DIR/"
    ok "Copied to macos-builds/"
else
    printf '  Bundles: %s\n' "$BUNDLE_DIR"
fi

echo ""
