/**
 * Version information for friendly-zoo
 * Auto-generated by devkit - DO NOT EDIT
 */
export const STORY_VERSION = '0.0.1';
export const BUILD_DATE = '2026-06-30T13:03:22Z';
export const ENGINE_VERSION = '1.1.1';
export const VERSION_INFO = { version: STORY_VERSION, buildDate: BUILD_DATE, engineVersion: ENGINE_VERSION } as const;
