/**
 * Version information for friendly-zoo
 * Auto-generated by devkit - DO NOT EDIT
 */
export const STORY_VERSION = '0.0.1';
export const BUILD_DATE = '2026-07-11T16:38:07Z';
export const ENGINE_VERSION = '2.2.0';
export const VERSION_INFO = { version: STORY_VERSION, buildDate: BUILD_DATE, engineVersion: ENGINE_VERSION } as const;
