/**
 * Version information for friendly-zoo
 * Auto-generated by sharpee - DO NOT EDIT
 */
export const STORY_VERSION = '0.0.1';
export const BUILD_DATE = '2026-06-28T00:00:00Z';
export const ENGINE_VERSION = '2.0.0';
export const VERSION_INFO = { version: STORY_VERSION, buildDate: BUILD_DATE, engineVersion: ENGINE_VERSION } as const;
