/**
 * Version information for familyzoo
 * Auto-generated by sharpee - DO NOT EDIT
 */
export const STORY_VERSION = '2.0.0';
export const BUILD_DATE = '2026-07-04T01:07:03Z';
export const ENGINE_VERSION = '2.0.0';
export const VERSION_INFO = { version: STORY_VERSION, buildDate: BUILD_DATE, engineVersion: ENGINE_VERSION } as const;
