/**
 * Version information for familyzoo
 * Auto-generated by sharpee - DO NOT EDIT
 */
export const STORY_VERSION = '1.0.0';
export const BUILD_DATE = '2026-06-23T06:42:52Z';
export const ENGINE_VERSION = '1.0.0';
export const VERSION_INFO = { version: STORY_VERSION, buildDate: BUILD_DATE, engineVersion: ENGINE_VERSION } as const;
