/**
 * grammar-blocks.ts — GENERATED by `repokit grammar` from
 * packages/parser-en-us/grammar/standard-en-us.story (ADR-272 D4/D5).
 * DO NOT EDIT — edit the Chord source and regenerate; the freshness gate
 * (`repokit grammar --check`, run by `repokit verify`) fails the build on drift.
 *
 * Each entry is the action's `define action` block VERBATIM from the shipped
 * standard grammar, in definition order. Rendered by <GrammarBlock>.
 *
 * Public interface: grammarBlocks (action id -> block text).
 * Owner context: website stdlib reference (generated artifact).
 */

export const grammarBlocks: Record<string, string> = {
  "if.action.looking": "define action looking\n  grammar\n    look\n    l\n    look [around]",
  "if.action.examining": "define action examining\n  grammar\n    examine the target\n    x the target\n    inspect the target\n    check the target\n    view the target\n    observe the target\n    look at the target\n    look [carefully] at the target",
  "if.action.searching": "define action searching\n  grammar\n    search [carefully]\n    search the target\n    look in or inside the target\n    look through the target\n    rummage in or through the target",
  "if.action.dropping": "define action dropping\n  grammar\n    drop the item\n    discard the item\n    release the item\n    put down the item\n    throw away the item\n    let go of the item",
  "if.action.wearing": "define action wearing\n  grammar\n    wear the item\n    don the item\n    equip the item\n    put on the item",
  "if.action.taking_off": "define action taking_off\n  grammar\n    remove the item\n    doff the item\n    unequip the item\n    take off the item\n    take the item off",
  "if.action.taking": "define action taking\n  grammar\n    take the item\n    get the item\n    grab the item\n    acquire the item\n    collect the item\n    pick up the item\n    take up the item",
  "if.action.eating": "define action eating\n  grammar\n    eat the item\n    consume the item\n    devour the item\n    munch the item\n    nibble the item\n    munch on the item\n    nibble on the item",
  "if.action.drinking": "define action drinking\n  grammar\n    drink the item\n    sip the item\n    quaff the item\n    swallow the item\n    imbibe the item\n    drink from the target\n    sip from the target",
  "if.action.inserting": "define action inserting\n  grammar\n    put the item in or into or inside the container\n    insert the item in or into the container",
  "if.action.putting": "define action putting\n  grammar\n    put the item on or onto the supporter\n    hang the item on the hook\n    move the item to the destination\n    place the item in or into or inside the container\n    place the item on or onto the supporter",
  "if.action.reading": "define action reading\n  grammar\n    read the target\n    peruse the target\n    study the target",
  "if.action.inventory": "define action inventory\n  grammar\n    inventory\n    inv\n    i",
  "if.action.opening": "define action opening\n  grammar\n    open the door\n    open the container with or using the tool\n    unwrap the door\n    uncover the door\n    open up the door\n  the tool is an instrument",
  "if.action.closing": "define action closing\n  grammar\n    close the door\n    shut the door\n    cover the door",
  "if.action.switching_on": "define action switching_on\n  grammar\n    turn on the device\n    switch on the device\n    flip on the device\n    turn the device on\n    activate the device\n    start the device\n    power on the device",
  "if.action.switching_off": "define action switching_off\n  grammar\n    turn off the device\n    switch off the device\n    flip off the device\n    turn the device off\n    deactivate the device\n    stop the device\n    power off the device",
  "if.action.pushing": "define action pushing\n  grammar\n    push the target\n    press the target\n    shove the target\n    move the target\n    move the target north\n    move the target n\n    move the target south\n    move the target s\n    move the target east\n    move the target e\n    move the target west\n    move the target w\n    move the target northeast\n    move the target ne\n    move the target northwest\n    move the target nw\n    move the target southeast\n    move the target se\n    move the target southwest\n    move the target sw\n    move the target up\n    move the target u\n    move the target down\n    move the target d\n    move the target in\n    move the target inside\n    move the target out\n    move the target outside",
  "if.action.pulling": "define action pulling\n  grammar\n    pull the target\n    drag the target\n    yank the target\n    tug the target",
  "if.action.lowering": "define action lowering\n  grammar\n    lower the target",
  "if.action.raising": "define action raising\n  grammar\n    raise the target\n    lift the target",
  "if.action.waiting": "define action waiting\n  grammar\n    wait\n    z",
  "if.action.saving": "define action saving\n  grammar\n    save\n    save game",
  "if.action.restoring": "define action restoring\n  grammar\n    restore\n    load\n    load game\n    restore game",
  "if.action.restarting": "define action restarting\n  grammar\n    restart",
  "if.action.sleeping": "define action sleeping\n  grammar\n    sleep\n    nap\n    doze\n    rest\n    slumber",
  "if.action.quitting": "define action quitting\n  grammar\n    quit\n    q\n    exit game",
  "if.action.undoing": "define action undoing\n  grammar\n    undo",
  "if.action.scoring": "define action scoring\n  grammar\n    score\n    points",
  "if.action.version": "define action version\n  grammar\n    version",
  "if.action.help": "define action help\n  grammar\n    help\n    commands",
  "if.action.about": "define action about\n  grammar\n    about\n    info\n    credits",
  "if.action.giving": "define action giving\n  grammar\n    give the item to the recipient\n    give the recipient the item\n    offer the item to the recipient\n    hand the item to the recipient\n    hand the recipient the item",
  "if.action.showing": "define action showing\n  grammar\n    show the item to the recipient\n    show the recipient the item\n    display the item to the recipient\n    present the item to the recipient",
  "if.action.throwing": "define action throwing\n  grammar\n    throw the item at the target\n    throw the item\n    toss the item\n    hurl the item\n    throw the item to the recipient\n    toss the item at the target\n    toss the item to the recipient\n    hurl the item at the target\n    hurl the item to the recipient",
  "if.action.removing": "define action removing\n  grammar\n    take the item from the container with or using the tool\n    remove the item from the container\n    extract the item from the container\n  the tool is an instrument",
  "if.action.unlocking": "define action unlocking\n  grammar\n    unlock the door with or using the key\n    unlock the target\n    unsecure the target\n  the key is an instrument",
  "if.action.locking": "define action locking\n  grammar\n    lock the target\n    lock the target with or using the key\n    secure the target\n  the key is an instrument",
  "if.action.cutting": "define action cutting\n  grammar\n    cut the object with or using the tool\n    cut the target\n    slice the target\n    chop the target\n  the tool is an instrument",
  "if.action.attacking": "define action attacking\n  grammar\n    attack the target\n    kill the target\n    fight the target\n    slay the target\n    murder the target\n    hit the target\n    strike the target\n    break the target\n    smash the target\n    destroy the target\n    attack the target with or using the weapon\n    kill the target with or using the weapon\n    hit the target with or using the weapon\n    strike the target with or using the weapon\n  the weapon is an instrument",
  "if.action.digging": "define action digging\n  grammar\n    dig the location with or using the tool\n    dig the target\n  the tool is an instrument",
  "if.action.telling": "define action telling\n  grammar\n    tell the recipient about the topic\n    inform the recipient about the topic\n  the topic is a topic",
  "if.action.asking": "define action asking\n  grammar\n    ask the recipient about the topic\n    question the recipient about the topic\n    inquire of the recipient about the topic\n  the topic is a topic",
  "if.action.talking": "define action talking\n  grammar\n    talk to or with the target\n    speak to or with the target\n    chat with the target\n    converse with the target\n    tell me more\n    continue\n    go on",
  "if.action.exiting": "define action exiting\n  grammar\n    go out\n    exit\n    get out\n    leave\n    climb out\n    exit the container\n    get out of the container\n    climb out of the container\n    disembark\n    disembark the vehicle\n    get off the vehicle\n    alight",
  "if.action.going": "define action going\n  grammar\n    go the direction\n    walk the direction\n    run the direction\n    head the direction\n    travel the direction\n    the direction\n  directions\n    north or n\n    south or s\n    east or e\n    west or w\n    northeast or ne\n    northwest or nw\n    southeast or se\n    southwest or sw\n    up or u\n    down or d\n    in or inside\n    out or outside",
  "if.action.listening": "define action listening\n  grammar\n    hear\n    hear the target\n    listen\n    listen to the target",
  "if.action.turning": "define action turning\n  grammar\n    turn the target\n    rotate the target\n    twist the target",
  "if.action.touching": "define action touching\n  grammar\n    touch the target\n    rub the target\n    feel the target\n    pat the target\n    stroke the target\n    poke the target\n    prod the target",
  "if.action.smelling": "define action smelling\n  grammar\n    smell\n    sniff\n    smell the target\n    sniff the target",
  "if.action.entering": "define action entering\n  grammar\n    enter the portal\n    get in the portal\n    get into the portal\n    climb in the portal\n    climb into the portal\n    go in the portal\n    go into the portal\n    board the vehicle\n    get on the vehicle",
  "if.action.climbing": "define action climbing\n  grammar\n    climb the target\n    climb up the target\n    climb down the target\n    scale the target\n    ascend the target\n    descend the target",
  "if.action.again": "define action again\n  grammar\n    again\n    g",
  "if.action.hiding": "define action hiding\n  grammar\n    hide behind the target\n      means position behind\n    duck behind the target\n      means position behind\n    crouch behind the target\n      means position behind\n    hide under the target\n      means position under\n    duck under the target\n      means position under\n    crouch under the target\n      means position under\n    hide on the target\n      means position on\n    hide in the target\n      means position inside\n    hide inside the target\n      means position inside\n    duck inside the target\n      means position inside",
  "if.action.revealing": "define action revealing\n  grammar\n    stand up\n    come out\n    reveal myself\n    unhide\n    stop hiding",
};
