/**
 * Scheduler types for Daemons and Fuses (ADR-071)
 *
 * Daemons: Processes that run every turn
 * Fuses: Countdown timers that trigger after N turns
 */

import { ISemanticEvent, EntityId, SeededRandom } from '@sharpee/core';
import { WorldModel } from '@sharpee/world-model';

// Re-export SeededRandom from core for convenience
export { SeededRandom } from '@sharpee/core';

/**
 * Context passed to daemon and fuse handlers
 */
export interface SchedulerContext {
  /** The world model */
  world: WorldModel;

  /** Current turn number */
  turn: number;

  /** Seeded random number generator */
  random: SeededRandom;

  /** Player's current location */
  playerLocation: EntityId;

  /** Player entity ID */
  playerId: EntityId;
}

/**
 * A daemon is a function that runs every turn
 */
export interface Daemon {
  /** Unique identifier */
  id: string;

  /** Human-readable name for debugging */
  name: string;

  /** Condition for running (optional - if omitted, always runs) */
  condition?: (context: SchedulerContext) => boolean;

  /** The daemon's action - returns semantic events */
  run: (context: SchedulerContext) => ISemanticEvent[];

  /** Priority for ordering (higher = runs first, default 0) */
  priority?: number;

  /** If true, daemon removes itself after first successful run */
  runOnce?: boolean;

  /** Optional: return runner-specific state for serialization (ADR-123) */
  getRunnerState?: () => Record<string, unknown>;

  /** Optional: restore runner-specific state after deserialization (ADR-123) */
  restoreRunnerState?: (state: Record<string, unknown>) => void;
}

/**
 * A fuse is a countdown timer that triggers after N turns
 */
export interface Fuse {
  /** Unique identifier */
  id: string;

  /** Human-readable name for debugging */
  name: string;

  /** Turns until trigger (counts down each tick) */
  turns: number;

  /** What happens when it triggers - returns semantic events */
  trigger: (context: SchedulerContext) => ISemanticEvent[];

  /** Optional: entity this fuse is bound to (for automatic cleanup) */
  entityId?: EntityId;

  /** Optional: condition for ticking (if false, turn doesn't count down) */
  tickCondition?: (context: SchedulerContext) => boolean;

  /** What happens if cancelled before triggering (cleanup) */
  onCancel?: (context: SchedulerContext) => ISemanticEvent[];

  /** Priority for ordering multiple simultaneous triggers */
  priority?: number;

  /** If true, fuse repeats after triggering */
  repeat?: boolean;

  /** Original turns value for repeating fuses */
  originalTurns?: number;
}

/**
 * Runtime state for a daemon
 */
export interface DaemonState {
  id: string;
  isPaused: boolean;
  runCount: number;
  /** Runner-specific state for typed daemons (ADR-123) */
  runnerState?: Record<string, unknown>;
}

/**
 * Runtime state for a fuse
 */
export interface FuseState {
  id: string;
  turnsRemaining: number;
  isPaused: boolean;
  entityId?: EntityId;
  /** Skip the next tick after fuse is set, so countdown matches turns value */
  skipNextTick?: boolean;
}

/**
 * Info about an active daemon (for debugging/introspection)
 */
export interface DaemonInfo {
  id: string;
  name: string;
  isPaused: boolean;
  runCount: number;
  priority: number;
}

/**
 * Info about an active fuse (for debugging/introspection)
 */
export interface FuseInfo {
  id: string;
  name: string;
  turnsRemaining: number;
  isPaused: boolean;
  entityId?: EntityId;
  priority: number;
  repeat: boolean;
}

/**
 * Result of a scheduler tick
 */
export interface SchedulerResult {
  /** Events generated by daemons and fuses */
  events: ISemanticEvent[];

  /** IDs of fuses that triggered this tick */
  fusesTriggered: string[];

  /** IDs of daemons that ran this tick */
  daemonsRun: string[];
}

/**
 * Serializable scheduler state for save/load
 */
export interface SchedulerState {
  /** Current turn number */
  turn: number;

  /** Daemon states */
  daemons: DaemonState[];

  /** Fuse states */
  fuses: FuseState[];

  /** Random seed */
  randomSeed: number;
}

/**
 * Scheduler event types for lifecycle events
 */
export type SchedulerEventType =
  | 'daemon.registered'
  | 'daemon.removed'
  | 'daemon.paused'
  | 'daemon.resumed'
  | 'fuse.set'
  | 'fuse.triggered'
  | 'fuse.cancelled'
  | 'fuse.paused'
  | 'fuse.resumed';
