/**
 * version-stamp.ts — generates a story project's src/version.ts.
 *
 * browser-entry.ts imports STORY_VERSION/BUILD_DATE from `./version`.
 * An author project never gets this file from the platform build (the monorepo only
 * stamps stories/<name>), so the devkit standalone commands stamp it themselves:
 * `init-browser` seeds it alongside browser-entry.ts (so the import resolves
 * immediately), and `build` / `build-browser` refresh it on every build.
 *
 * Owner context: @sharpee/devkit — standalone (author-project) commands (ADR-185).
 * Public interface: stampVersion(projectDir, storyId).
 */

import * as fs from 'fs';
import * as path from 'path';

/**
 * Write `<projectDir>/src/version.ts` with the project's version and the build
 * timestamp — story facts only. Overwrites any existing file (it is marked
 * auto-generated). The engine version is deliberately absent: the running engine
 * is the only authority on it, so its readers import the stamped platform
 * constant instead of a build tool's copy.
 * @param projectDir the story project root (contains package.json + src/)
 * @param storyId    the project id, used only in the file's header comment
 */
export function stampVersion(projectDir: string, storyId: string): void {
  let storyVersion = '1.0.0';
  try {
    const pkg = JSON.parse(fs.readFileSync(path.join(projectDir, 'package.json'), 'utf-8'));
    if (pkg.version) storyVersion = pkg.version;
  } catch {
    // Keep the default.
  }
  const buildDate = new Date().toISOString().replace(/\.\d+Z$/, 'Z');
  fs.mkdirSync(path.join(projectDir, 'src'), { recursive: true });
  fs.writeFileSync(
    path.join(projectDir, 'src', 'version.ts'),
    `/**
 * Version information for ${storyId}
 * Auto-generated by sharpee - DO NOT EDIT
 */
export const STORY_VERSION = '${storyVersion}';
export const BUILD_DATE = '${buildDate}';
export const VERSION_INFO = { version: STORY_VERSION, buildDate: BUILD_DATE } as const;
`,
  );
}
