#!/bin/zsh
# Phase 1 git baseline: commit rhythm, tags, and the branch sets of the three
# clones. Mechanical — no interpretation, and no claim that a branch present in
# one clone and absent from another is dead.
set -e
out="/Volumes/Workspace/sharpee-corpus/retrospective/index-git.md"
main="/Users/david/repos/sharpee"
v1="/Users/david/repos/sharpee_v1"
v2="/Users/david/repos/sharpee_v2"

{
  echo "# Git baseline"
  echo
  echo "Generated by \`build-git-index.sh\`. Three clones share the initial commit"
  echo "\`d9003cf7\` (2025-03-29); \`sharpee_v1\` and \`sharpee_v2\` are older clones kept"
  echo "on disk, not forks."
  echo
  echo "## Repository totals"
  echo
  echo "| Clone | Commits on HEAD | First | Last | Branches | Tags |"
  echo "| --- | --- | --- | --- | --- | --- |"
  for repo in "$main" "$v1" "$v2"; do
    name="${repo:t}"
    commits=$(git -C "$repo" rev-list --count HEAD)
    first=$(git -C "$repo" log --reverse --format="%ad" --date=short | head -1)
    last=$(git -C "$repo" log -1 --format="%ad" --date=short)
    branches=$(git -C "$repo" branch -a --format="%(refname:short)" | wc -l | tr -d ' ')
    tags=$(git -C "$repo" tag | wc -l | tr -d ' ')
    echo "| $name | $commits | $first | $last | $branches | $tags |"
  done

  echo
  echo "## Commits per month (this repo, all branches)"
  echo
  echo "| Month | Commits | Bar |"
  echo "| --- | --- | --- |"
  git -C "$main" log --all --format="%ad" --date=format:"%Y-%m" | sort | uniq -c | sort -k2 | while read count month; do
    bar=""
    n=$((count / 5))
    [ "$n" -gt 60 ] && n=60
    for i in $(seq 1 $n); do bar="${bar}█"; done
    echo "| $month | $count | $bar |"
  done

  echo
  echo "## Tags (this repo)"
  echo
  git -C "$main" for-each-ref --sort=creatordate --format='- `%(refname:short)` — %(creatordate:short)' refs/tags

  echo
  echo "## Branches present in the older clones but not here"
  echo
  echo "Candidates for work that never reached this clone. Presence in an older"
  echo "clone is not evidence of abandonment — the reading phases check."
  echo
  git -C "$main" branch -a --format="%(refname:short)" | sed 's#^origin/##' | sort -u > /tmp/.branches-main-c86356
  for repo in "$v1" "$v2"; do
    echo "### ${repo:t}"
    echo
    git -C "$repo" branch -a --format="%(refname:short)" | sed 's#^origin/##' | sort -u > /tmp/.branches-other-c86356
    missing=$(comm -13 /tmp/.branches-main-c86356 /tmp/.branches-other-c86356)
    if [ -z "$missing" ]; then
      echo "None — every branch here also exists in the current clone."
    else
      echo "$missing" | sed 's/^/- `/;s/$/`/'
    fi
    echo
  done
  rm -f /tmp/.branches-main-c86356 /tmp/.branches-other-c86356
} > "$out"

echo "wrote $out ($(wc -l < "$out") lines)"
