/**
 * Browser entry point for thealderman — generated by Sharpee IDE.
 *
 * A starting point that wires this story into the browser client. Add any
 * story-specific channel/audio renderers before `client.start()` — see
 * stories/dungeo/src/browser-entry.ts for a fully-featured example.
 */

import { GameEngine } from '@sharpee/engine';
import { WorldModel, EntityType } from '@sharpee/world-model';
import { Parser } from '@sharpee/parser-en-us';
import { LanguageProvider } from '@sharpee/lang-en-us';
import { PerceptionService } from '@sharpee/stdlib';
import { BrowserClient, ThemeManager } from '@sharpee/platform-browser';
import { createStory } from './index';
import { STORY_VERSION, ENGINE_VERSION, BUILD_DATE } from './version';

const THEME_STORAGE_KEY = 'thealderman-theme';
ThemeManager.applyEarlyTheme(THEME_STORAGE_KEY);

/**
 * The one BrowserClient for this page. Constructed on first boot and
 * reused across restart reboots (ADR-248): the client owns the DOM
 * wiring, which must not be re-bound per boot.
 */
let client: BrowserClient | null = null;

async function start(): Promise<void> {
  // Fresh story instance per boot (ADR-248); config is read off the instance.
  const story = createStory();
  const config = story.config;
  const author = config.author;

  // Create browser client with story configuration (first boot only)
  if (!client) {
  client = new BrowserClient({
    storagePrefix: 'thealderman-',
    // ADR-248: RESTART reboots by re-running this entry's boot path.
    reboot: () => start(),
    defaultTheme: 'modern-dark',
    themes: [
      { id: 'modern-dark', name: 'Modern Dark' },
      { id: 'paper', name: 'Paper' },
    ],
    storyInfo: {
      title: config.title,
      description: config.description || '',
      authors: Array.isArray(author) ? author.join(', ') : author,
      version: STORY_VERSION,
      engineVersion: ENGINE_VERSION,
      buildDate: BUILD_DATE,
    },
  });

  client.initialize({
    statusLocation: document.getElementById('location-name'),
    statusScore: document.getElementById('score-turns'),
    textContent: document.getElementById('text-content'),
    mainWindow: document.getElementById('main-window'),
    commandInput: document.getElementById('command-input') as HTMLInputElement,
    saveDialog: document.getElementById('save-dialog') as HTMLDialogElement,
    restoreDialog: document.getElementById('restore-dialog') as HTMLDialogElement,
    startupDialog: document.getElementById('startup-dialog') as HTMLDialogElement,
    saveNameInput: document.getElementById('save-name-input') as HTMLInputElement,
    saveSlotsListEl: document.getElementById('save-slots-list'),
    restoreSlotsListEl: document.getElementById('restore-slots-list'),
    noSavesMessage: document.getElementById('no-saves-message'),
    startupSaveInfo: document.getElementById('startup-save-info'),
    menuBar: document.getElementById('menu-bar'),
  });
  }

  const world = new WorldModel();
  const player = world.createEntity('player', EntityType.ACTOR);
  world.setPlayer(player.id);

  const language = new LanguageProvider();
  const parser = new Parser(language);
  if (story.extendParser) story.extendParser(parser);
  if (story.extendLanguage) story.extendLanguage(language);

  const perceptionService = new PerceptionService();
  const engine = new GameEngine({ world, player, parser, language, perceptionService });

  client.connectEngine(engine, world);
  engine.setStory(story);
  engine.registerSaveRestoreHooks(client.getSaveRestoreHooks());

  await client.start();
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', start);
} else {
  start();
}
