/**
 * Version information for thealderman
 * Auto-generated by devkit - DO NOT EDIT
 */
export const STORY_VERSION = '0.1.0';
export const BUILD_DATE = '2026-06-19T05:18:21Z';
export const ENGINE_VERSION = '1.0.0';
export const VERSION_INFO = { version: STORY_VERSION, buildDate: BUILD_DATE, engineVersion: ENGINE_VERSION } as const;
