#Requires -Version 5.1
<#
.SYNOPSIS
    Build a Zifmia release (frontend runner + Tauri MSI installer).

.DESCRIPTION
    Full pipeline using tsf for TypeScript compilation:
      1. Update version files
      2. tsf build --target local,esm (TypeScript compilation)
      3. Bundle runner frontend (esbuild via tsf loader)
      4. cargo tauri build - MSI installer

.PARAMETER Theme
    Zifmia theme name. Default: classic-light.

.PARAMETER Version
    Explicit version string (e.g. 0.9.91).
    If omitted, reads from packages/sharpee/package.json.

.PARAMETER SkipPlatform
    Skip steps 1-2 (versions + TypeScript compilation).

.PARAMETER SkipFrontend
    Skip steps 1-3 entirely, go straight to cargo tauri build.

.PARAMETER Debug
    Build a debug (unoptimised) Tauri binary instead of release.

.EXAMPLE
    .\build-release.ps1
    .\build-release.ps1 -Theme modern-dark
    .\build-release.ps1 -SkipPlatform
    .\build-release.ps1 -SkipFrontend
#>
param(
    [ValidateSet('classic-light', 'modern-dark', 'retro-terminal', 'paper')]
    [string]$Theme = 'classic-light',

    [string]$Version,

    [switch]$SkipPlatform,

    [switch]$SkipFrontend,

    [switch]$Debug
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
$ScriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Definition
$RepoRoot   = (Resolve-Path "$ScriptDir\..\..").Path
$SrcTauri   = Join-Path $ScriptDir 'src-tauri'
$RunnerDist = Join-Path $RepoRoot  'dist\runner'
$TsfCli     = Resolve-Path (Join-Path $RepoRoot '..\tsf\dist\cli\index.js') -ErrorAction SilentlyContinue
$BundleScript = Join-Path $ScriptDir 'scripts\bundle-runner.cjs'

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
function Write-Step($msg) { Write-Host "`n=== $msg ===" -ForegroundColor Cyan }
function Write-Ok($msg)   { Write-Host "  [OK] $msg" -ForegroundColor Green }

# Write file as UTF-8 without BOM (PS 5.1's -Encoding UTF8 adds BOM)
function Write-Utf8NoBom([string]$Path, [string]$Content) {
    [System.IO.File]::WriteAllText($Path, $Content, (New-Object System.Text.UTF8Encoding $false))
}

function Assert-Command($Name) {
    if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
        Write-Host "$Name is not installed or not on PATH." -ForegroundColor Red
        exit 1
    }
}

# ---------------------------------------------------------------------------
# Prerequisites
# ---------------------------------------------------------------------------
Assert-Command 'node'
Assert-Command 'cargo'

if (-not $TsfCli) {
    Write-Host "tsf CLI not found at ..\tsf\dist\cli\index.js" -ForegroundColor Red
    Write-Host "Build tsf first: cd ..\tsf && npm run build" -ForegroundColor Yellow
    exit 1
}

$tauriVer = & cargo tauri --version 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host 'cargo-tauri CLI not found. Install with: cargo install tauri-cli' -ForegroundColor Red
    exit 1
}
Write-Host "Tauri CLI: $tauriVer" -ForegroundColor DarkGray
Write-Host "tsf CLI:   $TsfCli" -ForegroundColor DarkGray

# ===================================================================
# Step 1 - Version updates
# ===================================================================
if (-not $SkipFrontend -and -not $SkipPlatform) {
    Write-Step 'Step 1: Update Versions'

    $buildDate = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')

    if ($Version) {
        $sharpeeVersion = $Version
    } else {
        $pkgJson = Get-Content "$RepoRoot\packages\sharpee\package.json" -Raw | ConvertFrom-Json
        $base = ($pkgJson.version -replace '-.*', '')
        $sharpeeVersion = "$base-beta"
    }

    $nativeVersion = $sharpeeVersion -replace '-.*', ''

    # packages/sharpee/package.json
    $sharpeePkg = Join-Path $RepoRoot 'packages\sharpee\package.json'
    $json = Get-Content $sharpeePkg -Raw | ConvertFrom-Json
    $json.version = $sharpeeVersion
    Write-Utf8NoBom $sharpeePkg ($json | ConvertTo-Json -Depth 10)
    Write-Ok "sharpee $sharpeeVersion"

    # packages/zifmia/package.json
    $zifmiaPkg = Join-Path $RepoRoot 'packages\zifmia\package.json'
    $json = Get-Content $zifmiaPkg -Raw | ConvertFrom-Json
    $json.version = $sharpeeVersion
    Write-Utf8NoBom $zifmiaPkg ($json | ConvertTo-Json -Depth 10)

    # packages/zifmia/src/version.ts
    $versionTs = Join-Path $RepoRoot 'packages\zifmia\src\version.ts'
    $versionContent = @"
/**
 * Version information for zifmia client
 * Auto-generated by build-release.ps1 - DO NOT EDIT
 */
export const CLIENT_VERSION = '$sharpeeVersion';
export const BUILD_DATE = '$buildDate';
export const ENGINE_VERSION = '$sharpeeVersion';
export const VERSION_INFO = { version: CLIENT_VERSION, buildDate: BUILD_DATE, engineVersion: ENGINE_VERSION } as const;
"@
    Write-Utf8NoBom $versionTs $versionContent

    # src-tauri/tauri.conf.json
    $tauriConf = Join-Path $SrcTauri 'tauri.conf.json'
    $json = Get-Content $tauriConf -Raw | ConvertFrom-Json
    $json.version = $nativeVersion
    Write-Utf8NoBom $tauriConf ($json | ConvertTo-Json -Depth 10)

    # src-tauri/Cargo.toml
    $cargoToml = Join-Path $SrcTauri 'Cargo.toml'
    $content = Get-Content $cargoToml -Raw
    $content = $content -replace '(?m)^version = ".*"', "version = `"$nativeVersion`""
    Write-Utf8NoBom $cargoToml $content

    Write-Ok "zifmia $sharpeeVersion (native: $nativeVersion)"
} else {
    Write-Host "`n=== Step 1: Skipped ===" -ForegroundColor Yellow
}

# ===================================================================
# Step 2 - TypeScript compilation via tsf
# ===================================================================
if (-not $SkipFrontend -and -not $SkipPlatform) {
    Write-Step 'Step 2: TypeScript Compilation (tsf)'

    Push-Location $RepoRoot
    try {
        & node $TsfCli build --target local,esm --verbose
        if ($LASTEXITCODE -ne 0) {
            Write-Host 'tsf build failed.' -ForegroundColor Red
            exit 1
        }
    } finally {
        Pop-Location
    }
} else {
    Write-Host "`n=== Step 2: Skipped ===" -ForegroundColor Yellow
}

# ===================================================================
# Step 3 - Bundle runner frontend
# ===================================================================
if (-not $SkipFrontend) {
    Write-Step 'Step 3: Bundle Runner Frontend'

    & node $BundleScript --theme $Theme
    if ($LASTEXITCODE -ne 0) {
        Write-Host 'Runner bundling failed.' -ForegroundColor Red
        exit 1
    }
} else {
    Write-Host "`n=== Step 3: Skipped (--SkipFrontend) ===" -ForegroundColor Yellow
}

# Verify dist/runner exists before Tauri build
if (-not (Test-Path "$RunnerDist\index.html")) {
    Write-Host "Runner frontend not found at $RunnerDist. Run without -SkipFrontend first." -ForegroundColor Red
    exit 1
}

# ===================================================================
# Step 4 - Tauri build
# ===================================================================
Write-Step 'Step 4: Cargo Tauri Build'

Push-Location $SrcTauri
try {
    $tauriBuildArgs = @('tauri', 'build')
    if ($Debug) { $tauriBuildArgs += '--debug' }

    Write-Host "  cargo $($tauriBuildArgs -join ' ')" -ForegroundColor DarkGray
    & cargo @tauriBuildArgs

    if ($LASTEXITCODE -ne 0) {
        Write-Host 'Tauri build failed.' -ForegroundColor Red
        exit 1
    }
} finally {
    Pop-Location
}

# ===================================================================
# Summary
# ===================================================================
Write-Host ''
Write-Host '=== Build Complete ===' -ForegroundColor Green

$profile = if ($Debug) { 'debug' } else { 'release' }
$bundleDir = Join-Path $SrcTauri "target\$profile\bundle"

$msi = Get-ChildItem -Path "$bundleDir\msi\*.msi" -ErrorAction SilentlyContinue | Select-Object -First 1
if ($msi) {
    $sizeMB = [math]::Round($msi.Length / 1MB, 1)
    Write-Host "  MSI:  $($msi.FullName) ($sizeMB MB)" -ForegroundColor White
}

$nsis = Get-ChildItem -Path "$bundleDir\nsis\*.exe" -ErrorAction SilentlyContinue | Select-Object -First 1
if ($nsis) {
    $sizeMB = [math]::Round($nsis.Length / 1MB, 1)
    Write-Host "  NSIS: $($nsis.FullName) ($sizeMB MB)" -ForegroundColor White
}

if (-not $msi -and -not $nsis) {
    Write-Host "  Bundles: $bundleDir" -ForegroundColor White
}

Write-Host ''
